# Formats the OoT and MM game trees (games/oot, games/mm) with clang-format 14.
#
# For each game tree we format:
#
# *.c and *.cpp everywhere
# the decomp projects run clang-format on their C files, so decomp-owned
# sources are formatted too (same as upstream, which formatted soh/src/**.c)
# https://github.com/zeldaret/mm/blob/b7e5468ca16315a7e322055eff3d97fe980bbc25/format.py#L182
#
# *.h and *.hpp EXCEPT under <game>/src/ and <game>/include/
# those are the decomp-owned header trees, which the decomp projects don't
# format (upstream excluded them as soh/src/** and soh/include/**)
#
# nothing under <game>/assets/ (autogenerated, don't fight it)
# nothing under <game>/build/ (build output)
#
# .clang-format configs live at games/oot/.clang-format and
# games/mm/.clang-format; clang-format discovers them per-file.
#
# find -print0 | xargs -0 separates paths with NUL bytes, avoiding issues
# with spaces in paths. --verbose prints files being formatted and X out of
# Y status.

GAMES="games/oot games/mm"

if command -v clang-format-14 > /dev/null 2>&1; then
    CLANG_FORMAT=clang-format-14
elif [ -x ./clang-format.exe ]; then
    CLANG_FORMAT=./clang-format.exe
elif command -v clang-format > /dev/null 2>&1 && clang-format --version | grep -q " 14\."; then
    CLANG_FORMAT=clang-format
else
    echo "error: clang-format 14 not found (install clang-format-14, or run run-clang-format.ps1 on Windows to download it)" >&2
    exit 1
fi

# Guard against this gate silently becoming a no-op again: every game tree
# must exist, or the paths in this script are stale.
for game in $GAMES; do
    if [ ! -d "$game" ]; then
        echo "error: $game does not exist — the paths in this script are stale" >&2
        exit 1
    fi
done

list_files() {
    for game in $GAMES; do
        find "$game" -type f \( -name "*.c" -o -name "*.cpp" -o \( \( -name "*.h" -o -name "*.hpp" \) ! -path "$game/src/*" ! -path "$game/include/*" \) \) ! -path "$game/assets/*" ! -path "$game/build/*" "$@"
    done
}

# Guard against this gate silently becoming a no-op again: an empty file list
# means the paths above no longer match the repo layout, and must be an error.
count=$(list_files | wc -l)
if [ "$count" -eq 0 ]; then
    echo "error: found no files to format — the paths in this script are stale" >&2
    exit 1
fi

list_files -print0 | xargs -0 "$CLANG_FORMAT" -i --verbose
