Using Namespace System
$url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/LLVM-14.0.6-win64.exe"
$llvmInstallerPath = ".\LLVM-14.0.6-win64.exe"
$clangFormatFilePath = ".\clang-format.exe"
$requiredVersion = "clang-format version 14.0.6"
$currentVersion = ""

function Test-7ZipInstalled {
    $sevenZipPath = "C:\Program Files\7-Zip\7z.exe"
    return Test-Path $sevenZipPath -PathType Leaf
}

if (Test-Path $clangFormatFilePath) {
    $currentVersion = & $clangFormatFilePath --version
    if (-not ($currentVersion -eq $requiredVersion)) {
        # Delete the existing file if the version is incorrect
        Remove-Item $clangFormatFilePath -Force
    }
}

if (-not (Test-Path $clangFormatFilePath) -or ($currentVersion -ne $requiredVersion)) {
    if (-not (Test-7ZipInstalled)) {
        Write-Host "7-Zip is not installed. Please install 7-Zip and run the script again."
        exit
    }

    $wc = New-Object net.webclient
    $wc.Downloadfile($url, $PSScriptRoot + $llvmInstallerPath)

    $sevenZipPath = "C:\Program Files\7-Zip\7z.exe"
    $specificFileInArchive = "bin\clang-format.exe"
    & "$sevenZipPath" e $llvmInstallerPath $specificFileInArchive

    Remove-Item $llvmInstallerPath -Force
}

# Format the OoT and MM game trees. Mirrors run-clang-format.sh:
# - *.c / *.cpp everywhere (the decomp projects format their own C files)
# - *.h / *.hpp except the decomp-owned <game>\src\ and <game>\include\ header trees
# - nothing under <game>\assets\ (autogenerated) or <game>\build\
$basePath = (Resolve-Path .).Path
$games = @("games\oot", "games\mm")

$files = @()
foreach ($game in $games) {
    if (-not (Test-Path "$basePath\$game" -PathType Container)) {
        Write-Host "error: $game does not exist - the paths in this script are stale"
        exit 1
    }
    $files += Get-ChildItem -Path "$basePath\$game" -Recurse -File `
        | Where-Object { ($_.Extension -eq '.c' -or $_.Extension -eq '.cpp' -or `
                          (($_.Extension -eq '.h' -or $_.Extension -eq '.hpp') -and `
                           (-not ($_.FullName -like "*\$game\src\*" -or $_.FullName -like "*\$game\include\*")))) -and `
                         (-not ($_.FullName -like "*\$game\assets\*" -or $_.FullName -like "*\$game\build\*")) }
}

# Guard against this gate silently becoming a no-op again: an empty file list
# means the paths above no longer match the repo layout, and must be an error.
if ($files.Length -eq 0) {
    Write-Host "error: found no files to format - the paths in this script are stale"
    exit 1
}

# Format in batches: one clang-format process per file is very slow on Windows
$batchSize = 40
for ($i = 0; $i -lt $files.Length; $i += $batchSize) {
    $batch = $files[$i..([Math]::Min($i + $batchSize, $files.Length) - 1)]
    $last = $batch[-1].FullName.Substring($basePath.Length + 1)
    Write-Host "Formatting [$([Math]::Min($i + $batchSize, $files.Length))/$($files.Length)] ... $last"
    .\clang-format.exe -i ($batch | ForEach-Object { $_.FullName })
}
