/**
 * @file main.cpp
 * @brief RedShip unified executable entry point
 *
 * Single executable architecture for running OoT and MM.
 * Both games are compiled as object libraries with namespaced symbols
 * (OoT_* and MM_*) and linked into this single binary.
 *
 * Uses GameRunner (composable lifecycle) to manage game transitions.
 *
 * Usage:
 *   redship --game oot    # Run Ocarina of Time
 *   redship --game mm     # Run Majora's Mask
 *   redship --test <name> # Run integration tests
 *   redship               # Run Ocarina of Time (default)
 */

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <csignal>
#include <exception>
#include <filesystem>
#include <string>

#include "game.h"
#include "game_lifecycle.h"
#include "context.h"
#include "ComboSpoilerWindow.h"   // Combo_SpoilerWindow_Init (#496, ADR 0008)
#include "combo_mm_options_page.h" // Combo_MMOptionsPages_Init (#497/#499, ADR 0004)
#include "ComboSettingsWindow.h"  // Combo_ComboSettingsWindow_Init (#498, ADR 0011 inc 2)
#include "ComboTrackerWindow.h"   // Combo_TrackerWindow_Init (#458, ADR 0008)
#include "entrance.h"
#include "mod_archives.h" // #593 — user mod archives must survive a game switch
#include "save.h" // rsbs::SaveManager — unified .redsave save-directory wiring
#include "rsbs_version.h"
#include "test_runner.h"
#include "integration_test_hooks.h"
#include "archive_check.h"
#include "array_reader_agreement.h" // #604: both games' vertex readers must agree before anything draws
#include "headless_crash.h"
#include "test_window_focus.h" // test windows never take focus (lane F1)

#include <SDL2/SDL_messagebox.h>
#include <ship/Context.h>
#include <ship/resource/ResourceManager.h>
#include <ship/resource/archive/ArchiveManager.h>

// ============================================================================
// Resource archive hot-swap for cross-game switches (issue #154)
// ============================================================================

extern "C" {
// Records an archive path in MM's archive-origin registry (RecordMMArchivePath,
// games/mm/2s2h/GameExports_SingleExe.cpp) — the predicate the per-archive
// Room/Cutscene/Path/Array dispatcher and ResourceMgr_ListFilesForGame key on.
// Declared here rather than included: that TU's headers are not on this
// target's include path.
void MM_RecordArchivePath(const char* path);
}

static const char* ArchiveAppName(GameId game) {
    switch (game) {
        case GAME_OOT:
            return "soh";
        case GAME_MM:
            return "2s2h";
        default:
            return nullptr;
    }
}

// #577 M1: the curated cross-game archive a game DRAWS from, named for that
// game (its host): redship-oot.o2r carries MM-origin models for OoT,
// redship-mm.o2r OoT-origin models for MM. Both are generated by
// GenerateRedshipOtr (scripts/make_redship_otr.py) from
// assets/crossgame/manifest.txt, whose direction column picks the half.
static const char* CuratedArchiveName(GameId host) {
    switch (host) {
        case GAME_OOT:
            return "redship-oot.o2r";
        case GAME_MM:
            return "redship-mm.o2r";
        default:
            return nullptr;
    }
}

// Mount @p host's curated half with @p host's identity.
//
// IDENTITY IS BEHAVIOUR here, not a label. RsbsMMArchiveFactoryDispatcher
// parses Room/Cutscene/Path/Array resources with MM's reader exactly when the
// OWNING archive is recorded as MM's, and ResourceMgr_ListFilesForGame files a
// path under the game its owner belongs to. So the MM half is recorded through
// MM's own registry — BEFORE it is added, so no load can observe it mounted
// but unrecorded — and the OoT half is simply not recorded, which is what makes
// an archive OoT's.
//
// Called right after the host's base archives and before its mods (see the
// callers): the curated paths are absent from the host's base archives by
// construction (the generator refuses a collision with any of them --
// oot.o2r, soh.o2r and, when extracted, oot-mq.o2r for OoT; mm.o2r and
// 2ship.o2r for MM -- as they stood at generation time), so their relative order
// does not matter, but a player's mod must still be able to restyle a foreign
// model, so mods stay last. The source game's own base archive wins those
// same paths back whenever the source game is the one arriving, because every
// switch re-adds the arriving game's base archives — so a curated path is
// always owned by an archive of the RUNNING game's identity.
//
// Absent is normal (a tree that never ran GenerateRedshipOtr, or a packaged
// build — see #806): foreign models then fall back to their model-less
// stand-ins, exactly as before #577.
static void MountCuratedArchive(Ship::ArchiveManager& archiveManager, GameId host) {
    const char* name = CuratedArchiveName(host);
    const char* appName = ArchiveAppName(host);
    if (name == nullptr || appName == nullptr) {
        return;
    }
    const std::string path = Ship::Context::LocateFileAcrossAppDirs(name, appName);
    if (path.empty() || !std::filesystem::exists(path)) {
        return;
    }

    if (host == GAME_MM) {
        MM_RecordArchivePath(path.c_str());
    }
    if (archiveManager.AddArchive(path)) {
        printf("[RSBS] Cross-game archive ready (%s identity): %s\n", Game_ToString(host), path.c_str());
    } else {
        fprintf(stderr, "[RSBS] Warning: failed to load cross-game archive %s; foreign models in %s keep their "
                        "model-less stand-ins\n",
                path.c_str(), Game_ToString(host));
    }
}

static void ReapplyModArchives(Ship::ArchiveManager& archiveManager, GameId targetGame);

// Not static: declared in src/common/mod_archives.h so the #593 lock
// (src/common/tests/test_curated_archive_order.c) can drive THIS function
// rather than a copy of it.
extern "C" void Combo_EnsureGameArchivesLoaded(GameId targetGame) {
    auto ctx = Ship::Context::GetInstance();
    if (!ctx || !ctx->GetResourceManager()) return;
    auto archiveManager = ctx->GetResourceManager()->GetArchiveManager();
    if (!archiveManager) return;

    struct ArchiveEntry { const char* filename; bool useLocate; };
    const char* appName = ArchiveAppName(targetGame);
    std::vector<ArchiveEntry> entries;

    switch (targetGame) {
        case GAME_OOT:
            entries = {{"oot.o2r", true}, {"oot-mq.o2r", true}, {"soh.o2r", false}};
            break;
        case GAME_MM:
            entries = {{"mm.o2r", true}, {"2ship.o2r", false}};
            break;
        default:
            return;
    }

    for (const auto& entry : entries) {
        std::string path = entry.useLocate
            ? Ship::Context::LocateFileAcrossAppDirs(entry.filename, appName)
            : Ship::Context::GetPathRelativeToAppBundle(entry.filename);

        if (path.empty() || !std::filesystem::exists(path)) continue;

        auto archive = archiveManager->AddArchive(path);
        if (archive) {
            printf("[RSBS] Archive ready: %s\n", path.c_str());
        } else {
            fprintf(stderr, "[RSBS] Warning: Failed to load archive: %s\n", path.c_str());
        }
    }

    // #577 M1: the arriving game's curated cross-game half, after its base
    // archives and before its mods.
    MountCuratedArchive(*archiveManager, targetGame);

    ReapplyModArchives(*archiveManager, targetGame);
}

// The boot half of the above: the booted game's own Init has already mounted
// its base archives and mods, so this adds the curated half and puts the mods
// back on top of it (declared in src/common/mod_archives.h).
extern "C" void Combo_MountCuratedArchive(GameId host) {
    auto ctx = Ship::Context::GetInstance();
    if (!ctx || !ctx->GetResourceManager()) return;
    auto archiveManager = ctx->GetResourceManager()->GetArchiveManager();
    if (!archiveManager) return;

    MountCuratedArchive(*archiveManager, host);
    ReapplyModArchives(*archiveManager, host);
}

static void ReapplyModArchives(Ship::ArchiveManager& archiveManager, GameId targetGame) {
    // #593: put the target game's mod archives back on top.
    //
    // ArchiveManager resolution is last-added-wins with no priority field
    // (ArchiveManager::AddArchive overwrites mFileToArchive[hash]
    // unconditionally), and that is the ONLY mechanism by which a user mod
    // overrides a base asset: both ports mount mods/ AFTER their base
    // archives. The base re-add above — which #154 requires — therefore puts
    // the base archives back on top and silently revokes every mod override.
    // OoT feels it on the first return trip (it mounts mods late, at GUI init)
    // and MM on its second arrival. Re-apply here so the post-switch mount
    // order matches the post-boot one.
    //
    // Only the TARGET game's mods: the base archives just re-added are the
    // target's, so the target's mods are exactly what got clobbered. The other
    // game's mods are still mounted above ITS base archives and are untouched.
    //
    // The registry (src/common/mod_archives.h) is fed by each port at mount
    // time, so this replays the player's ACTUAL enabled set in the player's
    // ACTUAL order. Re-globbing mods/ here would instead resurrect archives the
    // player disabled.
    //
    // Also run at boot by Combo_MountCuratedArchive, after the curated half, so
    // the mods sit above it there too (#577 M1).
    const int modCount = Combo_GetModArchiveCount(targetGame);
    for (int i = 0; i < modCount; i++) {
        const char* modPath = Combo_GetModArchive(targetGame, i);
        if (modPath == nullptr || modPath[0] == '\0') continue;

        if (!std::filesystem::exists(modPath)) {
            fprintf(stderr,
                    "[RSBS] WARNING: mod archive is gone since it was mounted, so its overrides are NOT active "
                    "after this switch: %s\n",
                    modPath);
            continue;
        }

        // #705: a registered mod can be a loose asset FOLDER, and re-adding one
        // re-walks it with libultraship's throwing directory iterator. A folder
        // that became unreadable since boot must cost that one mod, not the switch.
        std::shared_ptr<Ship::Archive> reapplied;
        try {
            reapplied = archiveManager.AddArchive(std::string(modPath));
        } catch (const std::exception& e) {
            fprintf(stderr, "[RSBS] WARNING: re-applying mod %s threw (%s)\n", modPath, e.what());
        }
        if (reapplied) {
            printf("[RSBS] Mod archive re-applied over %s base archives: %s\n", Game_ToString(targetGame), modPath);
        } else {
            // Loud on purpose. Silence here is the whole bug: the mod stays
            // listed as enabled in the menu while none of its assets apply.
            fprintf(stderr,
                    "[RSBS] WARNING: failed to re-apply mod archive after the switch; the base archives now "
                    "override it and this mod will NOT apply: %s\n",
                    modPath);
        }
    }
}

// ============================================================================
// Forward declarations for game ops providers
// ============================================================================

extern "C" {
    GameOps* OoT_GetGameOps(void);
    GameOps* MM_GetGameOps(void);
    // Whether the shared bring-up found an OoT game archive and ran OoT's
    // asset-dependent init (games/oot/soh/OTRGlobals.cpp, #330).
    int OoT_GameAssetsInitialized(void);
    // Freezes the departing game's SaveContext for an F10 hot swap and records
    // a return entrance for it (#364). Defined in
    // games/oot/soh/GameExports_SingleExe.cpp because only a game TU can
    // address gSaveContext; the policy itself is in src/common/switch.cpp.
    // Returns 0 when the freeze could not be performed — refuse the switch.
    int Combo_FreezeActiveGameForHotSwap(GameId departing);
    // In-app mm.o2r generation, offered at the start prompt when MM is
    // selected without a game archive (#317). Defined in
    // games/mm/2s2h/GameExports_SingleExe.cpp. Success is observed by
    // re-checking archive availability, not via a return value.
    void MM_Extract_OfferAndRun(void);
    // Registers MM's four tracker windows on the shared Gui (#392 bypass
    // surface, games/mm/2s2h/TrackersGuiSingleExe.cpp). Declared here rather
    // than included: TrackersGuiSingleExe.h lives under games/mm/2s2h, which is
    // not on this target's include path.
    void MM_TrackersGui_Init(void);
    // MM's .redsave slot-metadata descriptor (#765, games/mm/2s2h/
    // GameExports_SingleExe.cpp). Same include-path reason as above.
    void MM_SlotMeta_Register(void);
    // Build-version strings baked into each game library
    // (games/*/src/boot/build.c); declarations match each game's own header.
    extern const char OoT_gBuildVersion[];
    extern char MM_gBuildVersion[];
}

// ============================================================================
// Startup crash handler for crash diagnostics
//
// Covers the window before the Ship::Context singleton exists, which is the
// only stretch src/common/headless_crash.cpp cannot reach (it needs a context
// to claim libultraship's handler from). Once HeadlessCrash_ClaimAndInstall
// runs below, these are superseded.
// ============================================================================

#ifndef _WIN32
static void SignalHandler(int signal) {
    // The paired integration row tees fd 2 through a pipe from before this
    // handler is superseded; write the report to the real stderr, since the
    // tee's reader may never run again (a no-op for every other run).
    IntegrationTest_StderrCaptureRestoreForCrash();
    fprintf(stderr, "\n[CRASH] Signal received: %d\n", signal);
    switch (signal) {
        case SIGSEGV: fprintf(stderr, "[CRASH] SIGSEGV (Segmentation fault)\n"); break;
        case SIGABRT: fprintf(stderr, "[CRASH] SIGABRT (Abort)\n"); break;
        case SIGFPE:  fprintf(stderr, "[CRASH] SIGFPE (Floating point exception)\n"); break;
        case SIGILL:  fprintf(stderr, "[CRASH] SIGILL (Illegal instruction)\n"); break;
    }
    fflush(stderr);
    // Integration-test diagnostics only (release behavior unchanged): dump
    // the gameplay phase machine so a crash log is attributable to a repro
    // step even when it fires before libultraship's CrashHandler takes over
    // the signals, and exit 128+sig so CI can tell "crashed" from "test
    // failed". (Best effort — like the fprintf above, not strictly
    // async-signal-safe, but we are exiting anyway.)
    if (TestRunner_IsIntegrationTestMode()) {
        if (IntegrationTest_GetMode() == INT_TEST_GAMEPLAY_ROUNDTRIP) {
            IntegrationTest_LogGameplayState("signal");
        }
        _Exit(128 + signal);
    }
    _Exit(1);
}

static void InstallCrashHandler(void) {
    signal(SIGSEGV, SignalHandler);
    signal(SIGABRT, SignalHandler);
    signal(SIGFPE, SignalHandler);
    signal(SIGILL, SignalHandler);
}
#else
#include <windows.h>

static LONG WINAPI CrashHandler(EXCEPTION_POINTERS* exceptionInfo) {
    // As SignalHandler: the report goes to the real stderr, not the tee.
    IntegrationTest_StderrCaptureRestoreForCrash();
    fprintf(stderr, "\n[CRASH] Windows exception: 0x%08X\n",
            exceptionInfo->ExceptionRecord->ExceptionCode);
    fflush(stderr);
    return EXCEPTION_CONTINUE_SEARCH;
}

static void InstallCrashHandler(void) {
    SetUnhandledExceptionFilter(CrashHandler);
}

#endif

// ============================================================================
// Command line parsing
// ============================================================================

namespace {

GameId ParseGameArg(int argc, char** argv) {
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--game") == 0 && i + 1 < argc) {
            return Game_FromString(argv[i + 1]);
        }
        if (strncmp(argv[i], "--game=", 7) == 0) {
            return Game_FromString(argv[i] + 7);
        }
    }
    return GAME_NONE;
}

bool HasTestEntranceFlag(int argc, char** argv) {
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--test-entrance") == 0) {
            return true;
        }
    }
    return false;
}

bool HasHelpFlag(int argc, char** argv) {
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            return true;
        }
    }
    return false;
}

bool HasVersionFlag(int argc, char** argv) {
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--version") == 0) {
            return true;
        }
    }
    return false;
}

void PrintVersion(void) {
    // Base-port versions come from the linked game libraries so they can't
    // drift from what the archive/save compatibility checks actually enforce.
    printf("%s %s (%s)\n", RSBS_APP_NAME, RSBS_VERSION_STRING, RSBS_VERSION_CODENAME);
    printf("Base ports: Ship of Harkinian %s (OoT), 2 Ship 2 Harkinian %s (MM)\n",
           (const char*)OoT_gBuildVersion, (const char*)MM_gBuildVersion);
}

void PrintUsage(const char* progName) {
    printf("%s %s - Unified OoT+MM Executable\n\n", RSBS_APP_NAME, RSBS_VERSION_STRING);
    printf("Usage: %s [OPTIONS]\n\n", progName);
    printf("Options:\n");
    printf("  --game oot            Run Ocarina of Time\n");
    printf("  --game mm             Run Majora's Mask\n");
    printf("  --test <name>         Run unit tests\n");
    printf("  --integration-test <name>  Run integration tests (boots game)\n");
    printf("  --test-entrance       Use test entrance links (Mido's House)\n");
    printf("  --version             Show version information\n");
    printf("  --help, -h            Show this help message\n\n");
    printf("Unit test commands (--test):\n");
    printf("  boot-oot        Infrastructure test for OoT boot\n");
    printf("  boot-mm         Infrastructure test for MM boot\n");
    printf("  switch-oot-mm   Test OoT -> MM entrance switching\n");
    printf("  switch-mm-oot   Test MM -> OoT entrance switching\n");
    printf("  all             Run all unit tests\n");
    printf("  list            List all available tests\n\n");
    printf("Integration test commands (--integration-test):\n");
    printf("  int-boot-oot    Actually boot OoT and verify title screen\n");
    printf("  int-boot-mm     Actually boot MM and verify title screen\n\n");
    printf("Hotkeys:\n");
    printf("  F10              Switch between OoT and MM\n");
}

} // anonymous namespace

// ============================================================================
// Main entry point
// ============================================================================

int main(int argc, char** argv) {
    // Install crash handler
    InstallCrashHandler();

    // Check for version flag
    if (HasVersionFlag(argc, argv)) {
        PrintVersion();
        return 0;
    }

    // Check for help flag
    if (HasHelpFlag(argc, argv)) {
        PrintUsage(argv[0]);
        return 0;
    }

    // Check for unit test mode (--test)
    const char* testArg = TestRunner_ParseArgs(argc, argv);
    if (testArg != nullptr) {
        // Before any row can create a window: a test window is shown WITHOUT
        // activation, so a tier of ~180 processes never takes the keyboard from
        // the person at the workstation. Runs before the UI snapshot harness's own
        // SDL_SetHint (Session::BringUp), which it leaves in place. Normal play
        // never reaches this, so a player's window still comes to the front.
        // Locked by the test-window-no-activation row (test_window_focus.h).
        TestWindowFocus_ArmForTestMode("--test");
        // Fast-exit with the verdict: the chimera process heap-corrupts during
        // normal CRT teardown (0xC0000374 in the onexit static-destructor
        // chain — reproducible with just `redship --version` on Windows),
        // which would clobber the test's exit code AFTER the result was
        // decided. _Exit skips teardown so the verdict survives. This does
        // NOT hide the corruption: release runs still exit normally, and the
        // fault is tracked separately (teardown heap corruption, fault A in
        // docs/ci-gameplay-repro-postmortem.md follow-ups).
        int testResult = TestRunner_Run(testArg);
        fflush(stdout);
        fflush(stderr);
        _Exit(testResult);
    }

    // Check for integration test mode (--integration-test)
    const char* integrationTestArg = TestRunner_ParseIntegrationArgs(argc, argv);
    if (integrationTestArg != nullptr) {
        if (!TestRunner_SetupIntegrationTest(integrationTestArg)) {
            return 1; // Test not found
        }
        // Same policy as --test above: the integration tier boots the real game in
        // a window, and it must not take focus either. Set before the
        // Ship::Context below can create one.
        TestWindowFocus_ArmForTestMode("--integration-test");
        // Continue to game initialization - integration tests actually run the game
        printf("[INT-TEST] Integration test mode - will boot game with hooks\n");
    }

    // #604: one process draws both games' models, and a vertex array is parsed
    // by whichever game's 'OARR' reader owns the loader slot for its archive
    // (OoT's for OoT archives and the curated cross-game archive, MM's for MM's
    // once MM has initialized). The two readers are separate vendored copies; if
    // an upstream sync ever makes them fill a vertex differently, geometry
    // garbles with no error. Refuse to start instead. Needs no Ship::Context.
    if (Combo_ArrayReaders_BootCheck() != 0) {
        if (!TestRunner_IsIntegrationTestMode() && !HeadlessCrash_IsHeadless()) {
            SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "RedShipBlueShip cannot start",
                                     "This build's Ocarina of Time and Majora's Mask model readers disagree on "
                                     "vertex data (#604), so models would draw garbled. The details are in the log.",
                                     nullptr);
        }
        return 1;
    }

    // Initialize combo infrastructure
    Context_InitFrozenStates();
    ComboContext_Init();
    ComboEntrance_Init();

    // Register the one cross-game portal. The mask-shop door and Mido's House
    // are two OoT-side faces of the SAME portal (both return through MM
    // 0xC010), so they are mutually exclusive — registering both left the test
    // link's return leg dead and exited Mido's House into Hyrule Market
    // (#374). --test-entrance now selects the face instead of stacking on.
    const bool useTestPortal = HasTestEntranceFlag(argc, argv);
    Entrance_RegisterPortalLinks(useTestPortal);
    if (useTestPortal) {
        printf("Test entrance link registered (Mido's House <-> Clock Tower); "
               "the default mask-shop link is NOT registered\n");
    }

    // ========================================================================
    // Create Ship::Context singleton up front — before either game's Init
    // runs (issue #184, #271).
    //
    // The singleton is created UNINITIALIZED; the first game to boot runs
    // the shared subsystem bring-up on it (issues #329/#330): OoT through
    // OoT_Game_Init -> InitOTR (OTRGlobals adopts the singleton and
    // initializes it), MM through MM_Game_Init -> InitOTRForMMFirstBoot.
    // Creating the placeholder here means neither game depends on the
    // *other* having booted first — i.e. there is no "OoT must run before
    // MM" implicit ordering. The user can launch either `redship --game oot`
    // or `redship --game mm` cold, and the selected game's Init layers its
    // own factories/heaps onto the shared context.
    //
    // The display name (first argument) is RSBS's own identity so the window
    // title, crash dialog, and log name attribute tester reports to this
    // build instead of upstream SoH (issue #319). The app short name ("soh")
    // and config file ("shipofharkinian.json") are kept stable on purpose:
    // they pin the config and savestate directory to one location across
    // game switches. Re-keying these on the selected game would split a
    // single user's saves into two app-data folders the first time they
    // switched games. Asymmetric branding != asymmetric bootstrap; the
    // bootstrap itself is now game-agnostic.
    // ========================================================================
    fprintf(stderr, "[RSBS] About to create Ship::Context singleton...\n");
    fflush(stderr);
    auto shipContext = Ship::Context::CreateUninitializedInstance(
        RSBS_WINDOW_TITLE, "soh", "shipofharkinian.json");
    fprintf(stderr, "[RSBS] CreateUninitializedInstance returned: %p\n", (void*)shipContext.get());
    fflush(stderr);
    if (!shipContext) {
        fprintf(stderr, "[RSBS] FATAL: Failed to create Ship::Context singleton\n");
        return 1;
    }
    fprintf(stderr, "[RSBS] Ship::Context singleton created successfully at %p\n", (void*)shipContext.get());
    fflush(stderr);

    // Point the unified .redsave at the SAME directory the games write their own
    // per-game saves to. save.h documents this as the injection point where "the
    // game-integration follow-up injects the real per-app save directory" — that
    // follow-up never landed, so until now mSaveDir stayed at its bare relative
    // default "Save", resolved against the process WORKING DIRECTORY.
    //
    // Both games use Ship::Context::GetPathRelativeToAppDirectory("Save") (see
    // games/oot/soh/SaveManager.cpp GetFileName), so the two halves of a slot —
    // file{N+1}.sav and redship_slot{N}.redsave — only landed together when the
    // CWD happened to equal the app directory. Launch from a shortcut, a
    // debugger, or a packaged bundle and they silently fork: the .redsave for a
    // slot is written to, or looked for in, a different folder than the OoT save
    // it annotates, and the load is skipped with only a stderr line no
    // GUI-launched player ever sees.
    //
    // The "Save" default is deliberately left in place for the headless --test
    // path, which never creates a Ship::Context and relies on a CWD-relative
    // directory it can write to.
    rsbs::SaveManager::Instance().SetSaveDirectory(
        Ship::Context::GetPathRelativeToAppDirectory("Save"));

    // Claim crash handling BEFORE any game init runs (#388).
    //
    // Ship::CrashHandler ends every fatal fault in a modal dialog
    // (SDL_ShowSimpleMessageBox on Linux, MessageBoxA on Windows). With nobody
    // to click OK the process never returns from it, so on a runner a crash
    // presents as a CTest timeout with no exit code, no signal and no
    // traceback — which is how three "rando-gen hangs" hid a boot SIGSEGV and
    // cost a Linux bisect. This must happen here rather than after game init:
    // the #388 fault fired *inside* init (InitOTRForMMFirstBoot ->
    // ShipInit::InitAll), so a post-init reinstall would have missed it.
    // Interactive sessions are untouched and still get the dialog.
    HeadlessCrash_ClaimAndInstall();

    // ========================================================================
    // Set up GameRunner with composable lifecycle
    // ========================================================================

    fprintf(stderr, "[RSBS] Creating GameRunner...\n");
    fflush(stderr);
    GameRunner runner;
    GameRunner_Init(&runner);
    fprintf(stderr, "[RSBS] Registering OoT...\n");
    fflush(stderr);
    GameRunner_RegisterGame(&runner, GAME_OOT, OoT_GetGameOps());
    fprintf(stderr, "[RSBS] Registering MM...\n");
    fflush(stderr);
    GameRunner_RegisterGame(&runner, GAME_MM, MM_GetGameOps());
    fprintf(stderr, "[RSBS] Games registered\n");
    fflush(stderr);

    // Determine which game to run
    GameId selectedGame = GAME_NONE;

    // Integration tests override the game selection. Each integration test
    // boots its target game directly — no implicit OoT-first dance for MM
    // tests (#271). The harness has already created Ship::Context above, so
    // either game can be the first to initialize libultraship factories
    // and resources on top of it.
    if (TestRunner_IsIntegrationTestMode()) {
        selectedGame = TestRunner_GetIntegrationTestGame();
        printf("[INT-TEST] Using game from integration test: %s\n",
               Game_ToString(selectedGame));
    } else {
        selectedGame = ParseGameArg(argc, argv);
        if (selectedGame == GAME_NONE) {
            // No --game argument: boot straight into Ocarina of Time (landing
            // on its title/file-select menu) instead of prompting the user to
            // pick a game. MM is still reachable via `--game mm` or by
            // switching in-game (Happy Mask Shop <-> Clock Tower, or F10).
            selectedGame = GAME_OOT;
        }
    }

    // ========================================================================
    // Pre-flight archive check (#317): verify the selected game's ROM-derived
    // archives exist before any init. OoT can self-heal during its own init —
    // its in-app extractor (RunExtract) generates oot.o2r from a ROM. MM's
    // init has no equivalent, so the harness offers MM's extractor here
    // instead: it runs before any window exists (parentless SDL dialogs plus
    // a native file picker), generates mm.o2r from the user's ROM via the
    // bundled ZAPD_MM, and lets the boot continue. Integration tests stay
    // non-interactive: there a missing archive remains a hard failure.
    // Without this gate, a missing mm.o2r surfaces as a bare "Failed to
    // initialize game" on the console, which a GUI-launched user never sees.
    // ========================================================================
    if (selectedGame == GAME_MM && !ArchiveCheck_GameAvailable(GAME_MM)) {
        bool interactive = !TestRunner_IsIntegrationTestMode();
        bool available = false;
        if (interactive) {
            MM_Extract_OfferAndRun();
            available = ArchiveCheck_GameAvailable(GAME_MM);
        }
        if (!available) {
            ArchiveCheck_ReportMissing(GAME_MM, /*showDialog=*/interactive);
            return 1;
        }
    }

    // MM also needs its port-asset archive (2ship.o2r), which ships with the
    // package and cannot be generated from a ROM. Without it MM's early boot
    // dereferences null resources (fonts, boot-logo textures), so refuse up
    // front with an "incomplete install" message instead of crashing later.
    if (selectedGame == GAME_MM && !ArchiveCheck_PortArchiveAvailable(GAME_MM)) {
        ArchiveCheck_ReportMissingPortArchive(GAME_MM,
                                              /*showDialog=*/!TestRunner_IsIntegrationTestMode());
        return 1;
    }

    // Build filtered argv (remove our flags before passing to game)
    char** gameArgv = (char**)malloc(sizeof(char*) * (argc + 1));
    int gameArgc = 0;
    gameArgv[gameArgc++] = argv[0];

    for (int i = 1; i < argc; i++) {
        // Skip our flags
        if (strcmp(argv[i], "--game") == 0) {
            i++; // Skip value too
            continue;
        }
        if (strncmp(argv[i], "--game=", 7) == 0) {
            continue;
        }
        if (strcmp(argv[i], "--test-entrance") == 0) {
            continue;
        }
        if (strcmp(argv[i], "--test") == 0) {
            i++; // Skip value too
            continue;
        }
        if (strncmp(argv[i], "--test=", 7) == 0) {
            continue;
        }
        if (strcmp(argv[i], "--integration-test") == 0) {
            i++; // Skip value too
            continue;
        }
        if (strncmp(argv[i], "--integration-test=", 19) == 0) {
            continue;
        }
        gameArgv[gameArgc++] = argv[i];
    }
    gameArgv[gameArgc] = nullptr;

    // ========================================================================
    // Main game loop with hot-swap support via GameRunner
    // ========================================================================

    bool keepRunning = true;

    // Start the first game
    Combo_ClearGameSwitchRequest();
    Entrance_ClearPendingSwitch();

    GameOps* ops = GameRunner_GetOps(&runner, selectedGame);
    printf("Initializing %s...\n", ops ? ops->name : "Unknown");

    int initResult = GameRunner_StartGame(&runner, selectedGame, gameArgc, gameArgv);
    if (initResult != 0) {
        fprintf(stderr, "Error: Failed to initialize game (code %d)\n", initResult);
        free(gameArgv);
        return 1;
    }
    // Keep context's view of the current game in sync with the runner so that
    // cross-game entrance hooks dispatch against the right game (issue #170).
    Context_SetCurrentGame(selectedGame);

    // #577 M1: the booted game's curated cross-game half. Its own Init has
    // mounted its base archives (and mods) by now; every later arrival mounts
    // the arriving game's half through Combo_EnsureGameArchivesLoaded instead.
    // Without this, OoT could not reach an MM model before the first crossing
    // (mm.o2r is not mounted until then), which is the whole point of the
    // curated archive.
    Combo_MountCuratedArchive(selectedGame);

    // Cross-game spoiler panel (#496). Registered HERE, from the combo entry
    // point, rather than from either game's boot: it reads only gComboCtx, so
    // hanging it off MM's boot would hide it from the OoT-only session that
    // most needs it, and off OoT's boot would hide it from MM-only sessions
    // (ADR 0008). Whichever game started has created the Ship::Context and
    // its Gui by now; the call is a safe no-op if it has not.
    Combo_SpoilerWindow_Init();

    // MM randomizer options (#497 step 4, #499). Since 2026-09-27 they are menu
    // pages (Combo > MM Randomizer and Combo > MM Tricks), not a window, and the
    // page registrar publishes MM's two descriptor tables itself when OoT's menu
    // is built. This call is the same publication again (idempotent), so the
    // model is up in a session whose menu never built. The timing argument that
    // made the options a common-owned window still holds for where they are
    // drawn: they freeze at the creation event, so they must be reachable while
    // OoT is the running game, and OoT's menu is.
    Combo_MMOptionsPages_Init();

    // The combo settings pane (#498, ADR 0011 increment 2): the five tier-4
    // gCombo.Rando.* keys. Same seam, same reason as the spoiler above,
    // and the same timing argument -- these freeze into the paired world's
    // identity at OoT's generation, so the pane has to be reachable while OoT
    // is the running game or it can no longer change anything. Named here
    // rather than left to Combo_MMOptionsPages_Init (which also calls it, and it
    // is idempotent) so this list is the whole set of common-owned windows.
    Combo_ComboSettingsWindow_Init();

    // MM's four tracker windows (#535). Same seam, same reason: registration
    // used to hang off MM_Rando_Init, so the windows existed only once MM had
    // booted in this process and the Randomizer > Cross-Game rows that name
    // them resolved to nothing for the whole of a default OoT-first session.
    //
    // Safe before MM boots. MM_TrackersGui_Init needs a Ship::Context with a
    // window and a Gui (it no-ops otherwise) and nothing else of MM's: it
    // populates two static tables (Rando::StaticData::CheckNames,
    // safeItemsForInventorySlot) and constructs four windows whose InitElements
    // are empty but for the item-tracker settings pane, which reads only Config
    // and CVars. The tracker ICON load inside is gated on MM_Rando_AssetsReady()
    // and so is skipped here; MM_Rando_Init still calls this function once
    // mm.o2r is mounted, where registration is an idempotent no-op and the
    // icons load. Every registered window is MMActiveGated, so it draws nothing
    // while OoT is the running game.
    MM_TrackersGui_Init();

    // Combo tracker (#458). Same seam, and the seam is load-bearing here in
    // BOTH directions: the window's whole purpose is showing the INACTIVE
    // game's progress, so hanging it off either game's boot would hide it
    // from exactly the sessions that need it. Also registers both games'
    // tracker adapters (MM's shadow-offset descriptor, OoT's heap accessors).
    Combo_TrackerWindow_Init();

    // MM's slot metadata for the Combo > Save Files page (#765). Same seam, same
    // reason as the tracker: the page is drawn while OoT runs, and its only
    // other registrar (MM's SaveManager.cpp) is excluded from this link, so
    // without this every slot's MM half read "not started". Pure offsets; needs
    // nothing of MM's booted.
    MM_SlotMeta_Register();

    // Belt and braces: re-assert the unattended-safe handlers after game init.
    // The claim above already makes Ship::Context::InitCrashHandler a no-op
    // for both games, so nothing should have taken the handlers back — but
    // this costs nothing and the failure mode it guards against (a silent
    // re-registration turning every crash into a timeout again) is expensive
    // and hard to spot.
    HeadlessCrash_ClaimAndInstall();

    // Note: the previous MM-test detour (init OoT then SwitchTo MM) was
    // removed with #271 — MM integration tests now boot MM directly above.

    while (keepRunning) {
        // Run the active game
        ops = GameRunner_GetOps(&runner, GameRunner_GetActive(&runner));
        printf("Starting %s... (Press F10 to switch games)\n", ops ? ops->name : "Unknown");
        if (ops && ops->run) {
            ops->run();
        }

        // Integration test exit takes priority over game switching
        if (TestRunner_IsIntegrationTestMode() && IntegrationTest_ExitRequested()) {
            // The integration run's [FOCUS] line (lane F1): the game window is
            // still up here, so this reads whether it holds the keyboard after a
            // real boot, and armed=1 shows main armed the hint on this path too.
            TestWindowFocus_Probe(integrationTestArg);
            keepRunning = false;
            break;
        }

        // Check if we need to switch games
        GameId nextGame = GAME_NONE;
        uint16_t targetEntrance = 0;
        bool isEntranceSwitch = false;

        if (Entrance_IsCrossGameSwitch()) {
            // Entrance-based cross-game switch
            nextGame = Entrance_GetSwitchTargetGame();
            targetEntrance = Entrance_GetSwitchTargetEntrance();
            isEntranceSwitch = true;
            printf("\n=== Cross-game entrance detected ===\n");
            printf("Target: %s entrance 0x%04X\n",
                   Game_ToString(nextGame), targetEntrance);
        } else if (Combo_IsGameSwitchRequested()) {
            // F10 hotkey switch
            nextGame = Game_GetOther(GameRunner_GetActive(&runner));
        }

        // Handle the switch
        if (nextGame != GAME_NONE) {
            // Refuse the switch up front if the target game's ROM archives are
            // missing (#317). GameRunner_SwitchTo suspends the current game
            // before initializing the target, so a late init failure would
            // take down the whole app. Checking here keeps the current game
            // running: clear the pending switch, tell the user what's missing,
            // and loop back into the active game's run loop.
            if (!ArchiveCheck_GameAvailable(nextGame)) {
                ArchiveCheck_ReportMissing(nextGame, /*showDialog=*/!TestRunner_IsIntegrationTestMode());
                Combo_ClearGameSwitchRequest();
                Entrance_ClearPendingSwitch();
                printf("Switch to %s refused (missing game archive) — continuing %s.\n",
                       Game_ToString(nextGame), Game_ToString(GameRunner_GetActive(&runner)));
                continue;
            }

            // Same up-front refusal for the target game's port-asset archive
            // (2ship.o2r for MM): a switch into MM without it would fail in
            // MM_Game_Init and take down the whole app, or worse, boot into
            // null-resource crashes. Keep the current game running instead.
            if (!ArchiveCheck_PortArchiveAvailable(nextGame)) {
                ArchiveCheck_ReportMissingPortArchive(nextGame,
                                                      /*showDialog=*/!TestRunner_IsIntegrationTestMode());
                Combo_ClearGameSwitchRequest();
                Entrance_ClearPendingSwitch();
                printf("Switch to %s refused (missing port-asset archive) — continuing %s.\n",
                       Game_ToString(nextGame), Game_ToString(GameRunner_GetActive(&runner)));
                continue;
            }

            // The shared bring-up skips OoT's asset-dependent init (GUI, message
            // tables, item icons) when no OoT game archive was loaded at boot
            // (#330). If oot.o2r appeared on disk afterwards, the archive check
            // above passes but OoT would enter half-initialized — refuse and
            // ask for a restart instead.
            if (nextGame == GAME_OOT && !OoT_GameAssetsInitialized()) {
                Combo_ClearGameSwitchRequest();
                Entrance_ClearPendingSwitch();
                printf("Switch to OoT refused: oot.o2r was not present at startup — "
                       "restart RedShipBlueShip to play Ocarina of Time.\n");
                continue;
            }

            // F10 hot swap: freeze the DEPARTING game before we leave (#364).
            //
            // The entrance path freezes inside Combo_CheckEntranceSwitch, so by
            // the time we get here the departing game's blob is fresh. The F10
            // path had no such hook and froze nothing — yet the startup-entrance
            // branch below still consults Context_HasFrozenState(nextGame). Once
            // any entrance switch had populated a blob, every subsequent F10
            // return re-applied that stale snapshot: the player was rolled back
            // to whatever they had at the FIRST departure, with no error, no
            // title screen, and no visible symptom. Freezing here is what makes
            // the blob the launcher restores actually belong to this trip.
            //
            // If the freeze cannot be performed we refuse the switch outright
            // and keep the current game running, exactly like the archive checks
            // above. Switching anyway would hand the player a silent rollback,
            // which is strictly worse than a hotkey that appears not to work.
            if (!isEntranceSwitch) {
                GameId departingGame = GameRunner_GetActive(&runner);
                if (!Combo_FreezeActiveGameForHotSwap(departingGame)) {
                    Combo_ClearGameSwitchRequest();
                    Entrance_ClearPendingSwitch();
                    printf("Hot swap to %s refused: could not freeze %s state — continuing %s.\n",
                           Game_ToString(nextGame), Game_ToString(departingGame),
                           Game_ToString(GameRunner_GetActive(&runner)));
                    continue;
                }
            }

            GameOps* nextOps = GameRunner_GetOps(&runner, nextGame);
            printf("\n=== Switching to %s ===\n",
                   nextOps ? nextOps->name : "Unknown");

            // Clear switch state before transitioning
            Combo_ClearGameSwitchRequest();
            Entrance_ClearPendingSwitch();

            // Set the startup entrance, tagged with the destination game so
            // only that game can consume it — this prevents an MM entrance
            // (e.g. 0xD800) from leaking into OoT's entranceIndex and reading
            // gEntranceTable out of bounds (crash).
            //
            // Every re-entry cold-starts the target's gamestate chain, and on
            // the MM side that chain wipes whatever Game_Resume restored — the
            // only restore that reaches gameplay is the one Play_Init performs
            // when it consumes a pending startup entrance. So a hotkey (F10)
            // switch back into a game with frozen state must also set one,
            // using the frozen return entrance; otherwise the target silently
            // boots as a brand-new file at its title screen and the frozen
            // save is never consumed. A first-time hotkey entry (no frozen
            // state) keeps the plain title-screen boot.
            //
            // The blob this branch restores is now guaranteed to be current:
            // the hot-swap freeze above runs on every F10 departure, and the
            // target's Play_Init retires the blob as it consumes it
            // (Combo_ConsumeFrozenState). So a frozen state existing here means
            // "the player left this game and has not returned since", which is
            // exactly the condition the restore is for — not "this game was
            // left at some point in the past" (#364).
            if (isEntranceSwitch && targetEntrance != 0) {
                Entrance_SetStartupEntrance(targetEntrance, nextGame);
            } else if (!isEntranceSwitch && Context_HasFrozenState(nextGame)) {
                Entrance_SetStartupEntrance(Context_GetFrozenReturnEntrance(nextGame), nextGame);
            }

            // The integration rows' progress word (#793): no frame runs from
            // here until the target game's first one, so name the stage.
            if (TestRunner_IsIntegrationTestMode()) {
                IntegrationTest_StageProgress(nextGame == GAME_MM
                                                  ? "hand-off to MM (suspend OoT, archive swap, MM init/resume)"
                                                  : "hand-off to OoT (suspend MM, archive swap, OoT init/resume)");
                IntegrationTest_HandoffWedgeIfArmed();
            }

            // Hot-swap resource archives before game init/resume
            Combo_EnsureGameArchivesLoaded(nextGame);

            // GameRunner handles suspend/resume/init lifecycle
            int switchResult = GameRunner_SwitchTo(&runner, nextGame, gameArgc, gameArgv);
            if (switchResult != 0) {
                fprintf(stderr, "Error: Failed to switch to game (code %d)\n", switchResult);
                keepRunning = false;
            } else {
                // Track the new active game so cross-game entrance hooks
                // resolve to the correct side on the next round-trip (#170).
                Context_SetCurrentGame(nextGame);
            }
        } else {
            // Normal exit
            keepRunning = false;
        }
    }

    // Final cleanup — shutdown all games
    if (TestRunner_IsIntegrationTestMode()) {
        IntegrationTest_StageProgress("shutdown (GameRunner_ShutdownAll)");
    }
    GameRunner_ShutdownAll(&runner);

    free(gameArgv);

    // Return integration test result if in integration test mode.
    // Fast-exit for the same reason as the --test path above: normal CRT
    // teardown heap-corrupts (0xC0000374) and would overwrite the verdict
    // this run just produced. Games were shut down cleanly above; only the
    // static-destructor chain is skipped.
    if (TestRunner_IsIntegrationTestMode()) {
        int integrationResult = TestRunner_GetIntegrationTestResult();
        fflush(stdout);
        fflush(stderr);
        _Exit(integrationResult);
    }

    printf("Game exited normally.\n");
    return 0;
}
