/**
 * @file combo_logic.h
 * @brief The combo-logic coordinator and the engine query surface it drives
 *        (ADR 0010 increment 3, #645; O4 = COMPOSITION, operator 2026-09-17).
 *
 * ============================================================================
 * WHAT THIS IS, AND WHAT IT IS NOT
 * ============================================================================
 *
 * ADR 0010 answer O4 is ruled COMPOSITION: both ports' solvers stay
 * authoritative in their own dialects, and a game-header-free coordinator in
 * `src/common` owns exactly three things — the union bag of origin-tagged
 * items, the two origin-keyed placement tables, and the round loop. It never
 * evaluates a guard, never names an `RG_*` / `RI_*` / `RR_*` / `RC_*`, and
 * never touches a save. Everything that requires a game's enum in scope lives
 * behind the `ComboLogicEngine` vtable below, implemented in that game's own
 * single-exe TU beside its foreign-items TU.
 *
 * NOTHING HERE IS WIRED INTO A PRODUCTION PATH. No engine is registered by any
 * shipping TU at this commit; no creation seam calls the fill; no world is
 * generated by this code. It is the coordinator core plus its contract, locked
 * over synthetic stub engines in `src/common/tests/test_combo_logic.c`. The
 * deliberate absences are listed at the bottom of this header — read that list
 * before concluding something is missing by accident.
 *
 * ============================================================================
 * WHY A REGISTERED VTABLE AND NOT FIXED `extern "C"` SYMBOLS
 * ============================================================================
 *
 * The solver-inventory audit (§4.1) sketched the surface as two sets of fixed
 * C symbols (`OoT_Logic_Expand`, `MM_Logic_Expand`, ...). A REGISTERED VTABLE
 * IS REQUIRED INSTEAD, for one reason that decides it:
 *
 *   A ROM-free, display-free test must be able to drive the whole coordinator
 *   over engines it authors itself.
 *
 * Fixed symbols cannot be substituted: the real engines' TUs link into the same
 * binary as the tests (this is a single executable), so a test cannot provide
 * its own `OoT_Logic_Expand` without a duplicate-symbol error, and a test that
 * drove the REAL engines would need both ROMs, both graphs built, a display for
 * MM's crawl (audit §6.3), and a generated world — which is precisely the
 * dependency chain that has kept every pair-level assertion in this project
 * vacuous. With a vtable, `test_combo_logic.c` registers two small stub engines
 * whose reachability is a bitmask, and every claim below is falsifiable on the
 * `redship` tier in milliseconds.
 *
 * Two smaller reasons, both real: a build with only one game's engine TU linked
 * resolves cleanly (the missing origin simply has no engine, the same property
 * `Combo_RegisterForeignItemPool` exists for), and MM's snapshot/restore pair is
 * OPTIONAL, which a fixed-symbol surface can only express as a stub that lies.
 *
 * The cost is one indirect call per query, against an engine call that runs a
 * whole reachability search. It is not measurable.
 *
 * ============================================================================
 * THE BOUNDARY (ADR 0002)
 * ============================================================================
 *
 * Only game-neutral scalars cross: a `SharedItem` (origin tag + id), a HOST
 * CHECK ID, and the HOST'S ORIGIN GAME. Nothing else. `assumeOwnItem` and the
 * own-origin half of `place` receive ONLY ids from the receiving engine's own
 * id-space, because the coordinator routes by `item.originGame` before calling —
 * so ADR 0002 holds by construction, not by review. MM reports "check 201
 * reached"; the coordinator looks up `placement[MM][201] == SharedItem{OOT, id}`
 * and calls the OoT engine's `assumeOwnItem(id)`. No MM code ever sees that id.
 *
 * Host check ids live in each game's own check id-space and are never compared
 * across games: `(hostGame, hostCheck)` is the key, exactly as `(originGame,
 * name)` is the key in foreign_items.h for the same #356 reason.
 */

#ifndef RSBS_COMMON_COMBO_LOGIC_H
#define RSBS_COMMON_COMBO_LOGIC_H

#include "context.h"       // SharedItem, GameId
#include "foreign_items.h" // RSBS_COMBO_GOAL_*, RSBS_COMBO_RUNG_*, RSBS_ITEMCLASS_*

#ifdef __cplusplus
extern "C" {
#endif

/** Bumped when the vtable's shape or any call's contract changes. An engine
 *  registering a different value is REFUSED rather than called through — a
 *  half-updated engine would otherwise be diagnosed as a logic bug months
 *  later. This is a build-internal number: nothing here is serialized, so it is
 *  not .redsave format and carries no append-only obligation. */
#define RSBS_COMBO_LOGIC_ENGINE_ABI 1u

// ============================================================================
// Status codes — DIAGNOSTICS, NOT FORMAT
// ============================================================================
//
// Nothing in this header is serialized, so these values may be renumbered
// freely (unlike every value space in foreign_items.h). Combo_Logic_StatusName
// renders them; the fill and round results carry them.

#define RSBS_COMBO_LOGIC_OK 0
/** One or both engines are not registered. A paired fill requires BOTH: the
 *  combo is one game (one-game semantics), so a fill with one half missing
 *  would author a world whose other half was never decided. */
#define RSBS_COMBO_LOGIC_ERR_NO_ENGINE 1
/** Malformed request: NULL where a pointer is required, a negative count, an
 *  unpinned rung value, a bag item tagged GAME_NONE. */
#define RSBS_COMBO_LOGIC_ERR_BAD_REQUEST 2
/** The GOAL value is pinned but this build has no evaluator for it.
 *  RSBS_COMBO_GOAL_TRIFORCE_HUNT is the only such value today: it needs ADR
 *  0010 answer O10's ONE shared piece count across both worlds, which does not
 *  exist (epic #645 item 5). Refused loudly rather than silently evaluated as
 *  beat-both, which would ship a world whose stated goal is not the goal that
 *  was proved. */
#define RSBS_COMBO_LOGIC_ERR_UNSUPPORTED_GOAL 3
/** An engine's reachability is not monotone: an observable that may only grow
 *  within a round (its candidate-host count, or its crossing flag) DECREASED.
 *  Assumed fill and the trailing no-logic dump are unsound without monotonicity
 *  (ADR 0010 §2.3), so this is refused, never worked around. */
#define RSBS_COMBO_LOGIC_ERR_NON_MONOTONE 4
/** The round loop hit RSBS_COMBO_LOGIC_MAX_ROUND_ITERATIONS without an engine
 *  reporting "nothing new". Either an engine reports `changed` unconditionally,
 *  or the graph is far larger than the cap anticipates. Reported, never looped
 *  on — see the termination argument at the loop in combo_logic.c. */
#define RSBS_COMBO_LOGIC_ERR_NO_FIXPOINT 5
/** Dead end: an item had to be placed and no reached, unassigned host existed
 *  on either side, on every attempt. This is the failure the ATTEMPT LADDER
 *  above the coordinator answers with a deterministic re-roll (ADR 0010 §2.3);
 *  the coordinator's own retries are the batch roll-back inside one seed. */
#define RSBS_COMBO_LOGIC_ERR_NO_CANDIDATE 6
/** Every attempt placed the whole bag, and on none of them was the GOAL
 *  expression provable with the bag empty. The GOAL check is the fill's EXIT
 *  CONDITION (ADR 0010 D4), so this is a fill failure, not a warning. */
#define RSBS_COMBO_LOGIC_ERR_GOAL_UNPROVABLE 7
/** Under RSBS_COMBO_RUNG_ALL_REACHABLE only: the GOAL was provable but some
 *  placed host was not reached in the final round. */
#define RSBS_COMBO_LOGIC_ERR_NOT_ALL_REACHED 8
/** A fixed capacity was exceeded (bag size, placements per host game). */
#define RSBS_COMBO_LOGIC_ERR_CAPACITY 9
/** An engine refused a call it is contractually required to satisfy —
 *  `beginQuery` or `snapshot` returned 0, or `place` returned 0 for a host the
 *  engine had itself offered as a candidate. */
#define RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED 10

/** Its name ("ok", "no-engine", ...), or "(unknown)". Never NULL. */
const char* Combo_Logic_StatusName(int status);

// ============================================================================
// Fixed capacities
// ============================================================================

/** Bag items in one fill. The union bag is both games' last general ADVANCEMENT
 *  pass only (audit amendment 2) — OoT's remaining-advancement set plus MM's
 *  shuffled pool — so the real figure is low hundreds. */
#define RSBS_COMBO_LOGIC_BAG_CAP 512
/** Placements per HOST game. RAM only: see the placement-table note below. */
#define RSBS_COMBO_LOGIC_PLACEMENT_CAP 1024
/** Watchdog bound on one round's inner alternations. NOT the termination
 *  argument — convergence follows from monotonicity over a finite lattice; this
 *  bound exists to turn a VIOLATED premise into a diagnosis instead of a hang.
 *  The audit expects real convergence in two or three alternations (§4.3). */
#define RSBS_COMBO_LOGIC_MAX_ROUND_ITERATIONS 256
/** Default batch roll-backs within one seed before the fill gives up, mirroring
 *  OoT's own assumed-fill retry discipline (`fill.cpp:877-934`). The ATTEMPT
 *  LADDER above the coordinator is a different mechanism: it re-rolls the SEED.
 *  Conflating the two produced the silent-vanilla-revert bug class (ADR 0010
 *  §2.2), so they are named separately here. */
#define RSBS_COMBO_LOGIC_FILL_RETRIES 10

// ============================================================================
// THE ENGINE SURFACE
// ============================================================================
//
// ---------------------------------------------------------------------------
// WHO OWNS WHAT
// ---------------------------------------------------------------------------
//
// THE COORDINATOR owns: the union bag, both placement tables, the round loop,
// the assumed set, the RNG, the GOAL/rung evaluation, and the decision of WHEN
// an item counts as held. It owns occupancy: its table is the single authority
// on "is this host already assigned".
//
// AN ENGINE owns: its own region graph, its own condition dialect, its own
// simulated inventory, and its own save coupling. It answers questions about
// its own world and nothing else. It never inspects the coordinator's tables,
// never asks about the other game, and never decides anything about the fill.
//
// AN ENGINE MUST LEAVE UNTOUCHED, across a whole round:
//   - the player's live save, except through the snapshot/restore pair it
//     itself declares (see MM's bracket below);
//   - any RNG the world generation consumes. A query runs a VARIABLE number of
//     times per fill, so an engine that drew one random number inside a query
//     would make the world a function of the search's shape. The coordinator's
//     own RNG is private and seeded from the frozen identity (below).
//   - global state the OTHER engine reads. The two engines share a process;
//     they must not share state.
//
// ---------------------------------------------------------------------------
// CALL ORDER — THE ROUND
// ---------------------------------------------------------------------------
//
// One ROUND is one complete reachability evaluation under a partial placement P
// (the coordinator's tables) and an assumed set A (bag items not yet placed).
// The coordinator runs a round per bag item, plus one final round with A empty.
// Exactly this sequence, per round, for both engines:
//
//   for each side S in {OOT, MM}:            // OoT first, deterministically
//       if (S.snapshot) S.snapshot()         // BEFORE beginQuery: the restore
//       S.beginQuery()                       //   must undo beginQuery too
//   for each a in A:  side(a.originGame).assumeOwnItem(a.id)
//   repeat, bounded by RSBS_COMBO_LOGIC_MAX_ROUND_ITERATIONS:
//       changed  = OOT.expand()
//       changed |= exchange OoT-hosted, MM-origin items    // gated, below
//       changed |= MM.expand()
//       changed |= exchange MM-hosted, OoT-origin items    // gated, below
//   until !changed
//   read: crossingOpen, goalReached, reachedEmptyHosts, checkReached
//   for each side S, in reverse:
//       if (S.restore) { S.restore(); re-apply all of P[S] through S.place() }
//       S.endQuery()
//
// The re-apply runs ONLY for a side that restored. A side with no snapshot never
// lost anything, so re-placing there would be pure cost — and the cost is not
// small: it is one `place` per placement per round, and the fill runs a round
// per bag item.
//
// THE EXCHANGE GATES, stated as the travel they model (audit §4.5):
//   - An MM-origin item sitting in an OoT host reaches MM iff that host is
//     reached AND OoT's crossing is open (the player must be able to get to
//     MM to spend it).
//   - An OoT-origin item sitting in an MM host reaches OoT iff that host is
//     reached AND OoT's crossing is open (to get there at all) AND MM's
//     crossing is open (to get back).
//
// THE ARRIVAL GATE — a coordinator rule the audit did not state, taken here
// deliberately. The combo's file starts in OoT and MM is reached through the
// crossing, but MM's engine knows nothing about that: its graph root is
// reachable unconditionally in its own dialect (audit §4.5). So the coordinator
// applies the gate the MM engine cannot: while OoT's crossing is CLOSED, MM's
// hosts are not candidates and MM's goal does not count as reached. Without it,
// a world whose crossing never opens would host progression in a Termina the
// player can never enter, and `beat-either` would call that half proved. In
// practice OoT's crossing opens at sphere zero under default settings, which is
// exactly why this must be a rule rather than an observation.
//
// ---------------------------------------------------------------------------
// MM'S BRACKET (audit §4.4 / amendment 1)
// ---------------------------------------------------------------------------
//
// Every MM query, the "read-only" crawl included, writes MM's LIVE save. So one
// snapshot/restore brackets the WHOLE round, not each call, and the
// coordinator re-applies the side's whole placement table after the restore.
//
// It re-applies ALL of P[S], not only the placements made during the round,
// because that invariant holds no matter when the snapshot was taken: after
// every round, a restoring engine's state contains every placement the
// coordinator has decided. This is what makes `place` IDEMPOTENT a hard
// requirement rather than a nicety (see `place` below). The narrower reading —
// re-apply only what this round placed — is the same set in the fill's own
// shape, because the fill places BETWEEN rounds and never inside the bracket;
// re-applying the whole table is the reading that stays correct if a later
// consumer ever does place inside one.
//
// An engine whose queries are genuinely pure supplies NULL for both. OoT's is:
// `Logic::Reset(true)` detaches the save and the search runs against the
// detached copy (audit §4.2). OoT's one obligation is the inverse — re-point
// `Logic::mSaveContext` at the live save in `endQuery`, or the next in-game
// progressive give resolves against a stale simulated save (audit §1.8).

/**
 * One engine. Every function pointer except `snapshot`/`restore` is REQUIRED;
 * registration refuses a vtable with a hole rather than crashing at the first
 * round. `self` is passed to every call and is the engine's own opaque state —
 * NULL is legal and is what a real engine (whose state is file-static in its
 * own TU) passes. It exists so a test can register two stub engines that share
 * one set of function pointers.
 */
typedef struct ComboLogicEngine {
    /** Must equal RSBS_COMBO_LOGIC_ENGINE_ABI. */
    uint32_t abiVersion;
    /** Opaque engine state, passed to every call below. May be NULL. */
    void* self;

    /**
     * Begin one round. Reset the simulated inventory to the WORLD'S STARTING
     * INVENTORY and detach from anything this engine must not mutate.
     *
     * CALLED EXACTLY ONCE PER ROUND, before any other call of that round.
     *
     * THIS IS THE CALL THE OoT ENGINE CANNOT SKIP. `ReachabilitySearch` does
     * NOT reset OoT's `logic` singleton: a search run without
     * `Logic::Reset(true)` first INHERITS the previous search's simulated
     * inventory, and since the coordinator runs one round per bag item, that
     * would make every round after the first answer a question about a world
     * holding strictly more items than the round was asked about. The failure is
     * silent and it looks like the fill working.
     *
     * @return nonzero on success. Zero aborts the round with
     *         RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED.
     */
    int (*beginQuery)(void* self);

    /**
     * Grant one of THIS ENGINE'S OWN items into the simulated inventory — the
     * assumed-fill "pretend the player has it". `ownItemId` is always from this
     * engine's own id-space; the coordinator routed by origin before calling.
     *
     * "OWN ITEM" MEANS: an id this engine's own enum names, whose effect this
     * engine's own give path applies. It does NOT mean "an item found in this
     * game" — an MM-origin item found in an OoT chest is granted to the MM
     * engine, because MM is where that id means something.
     *
     * MAY BE CALLED REPEATEDLY, with the same id, within one round: once while
     * the assumed set is seeded and again whenever a crossing exchange delivers
     * it. Repeats must be harmless. It is called BETWEEN `expand()` calls, so
     * it must not invalidate whatever `expand` accumulated — it may only ADD.
     *
     * It must never REDUCE reachability. An engine whose give path can lower a
     * capacity, consume a resource or clear a flag breaks monotonicity, and
     * with it the soundness of the whole fill (ADR 0010 §2.3).
     */
    void (*assumeOwnItem)(void* self, uint16_t ownItemId);

    /**
     * One reachability expansion over this engine's own graph, under everything
     * granted so far this round.
     *
     * @return nonzero iff something became reachable that was not reachable at
     *         the previous `expand()` of this round (a region, a check, the
     *         crossing). Returning nonzero forever is a contract violation; the
     *         coordinator's watchdog reports it as
     *         RSBS_COMBO_LOGIC_ERR_NO_FIXPOINT rather than spinning.
     *
     * Called repeatedly until the coordinator sees no side change. It must be
     * safe to call with nothing new granted (answer: zero, cheaply).
     */
    int (*expand)(void* self);

    /**
     * Is the cross-game crossing reachable right now, from THIS engine's side?
     * OoT: `RegionTable(RR_MARKET_MASK_SHOP)->Child()`. MM:
     * `RR_CLOCK_TOWER_INTERIOR` in the reachable set. A region FACT, not a new
     * graph edge — neither port's region files change for increment 3 (audit
     * amendment 3). Pure read; never mutates.
     */
    int (*crossingOpen)(void* self);

    /**
     * Is `hostCheck` — an id in THIS engine's own check id-space — reached
     * right now? Pure read. The coordinator asks only about hosts this engine
     * itself reported or was given via `place`.
     */
    int (*checkReached)(void* self, uint16_t hostCheck);

    /**
     * The engine's candidate hosts: shuffled checks it owns that are REACHED
     * right now and that it does not consider already assigned.
     *
     * ORDER IS A CONTRACT. The list must be in a STABLE order that is a
     * function of the engine's graph alone — ascending check id, or fixed table
     * order — and NOT of the order items were granted this round. The
     * coordinator picks a host from this list with its own RNG, so an order
     * that depended on grant order would make the world depend on the search's
     * shape instead of on the seed, and the determinism rows would catch it only
     * sometimes.
     *
     * @param out NULL to count only (then `cap` is ignored).
     * @param cap capacity of `out`; at most `cap` ids are written.
     * @return the TOTAL number of candidate hosts, which may EXCEED `cap`. The
     *         return is the total in both the count-only and the write case, so
     *         the coordinator can tell truncation from exhaustion.
     *
     * The coordinator filters the result against its OWN tables before using
     * it, so an engine that over-reports (offering a host the coordinator has
     * already filled) costs nothing, and one that under-reports merely narrows
     * its own world. Occupancy has exactly one authority and it is not here.
     */
    int (*reachedEmptyHosts)(void* self, uint16_t* out, int cap);

    /**
     * Is THIS HALF'S goal reached right now? OoT: `RG_TRIFORCE` reached, i.e.
     * `CheckBeatable`'s condition. MM: Majora's Lair reached and Majora
     * defeated, through MM's own authored gate chain (ADR 0010 D1/D2).
     *
     * ONE HALF'S ANSWER ONLY. The coordinator composes the two under the frozen
     * GOAL value; an engine must never try to answer for the pair, and must
     * never widen its own half because the other half is unprovable (the OR is
     * never narrowed to an XOR — ADR 0010 §1.2).
     */
    int (*goalReached)(void* self);

    /**
     * Record that `hostCheck` — a host in THIS engine's check id-space — holds
     * `item`, which may be of EITHER origin.
     *
     *   - `item.originGame` == this engine's game: a real placement (OoT:
     *     `PlaceItemInLocation`; MM: the `RANDO_SAVE_CHECKS` write).
     *   - `item.originGame` == the other game: a JUNK COVER. The host's own
     *     table gets a legal local junk item and the foreign identity stays in
     *     the coordinator's table. A raw foreign id must never enter this
     *     engine's tables (ADR 0002).
     *
     * IT MUST NOT GRANT THE ITEM. Placing is not holding: the coordinator
     * decides when an item counts as held (`assumeOwnItem`, and the harvest of
     * own-origin items that `expand` does when their host becomes reached). An
     * engine that granted on place would make every placement instantly
     * available and the proof vacuous.
     *
     * IT MUST BE IDEMPOTENT for the same (hostCheck, item): the coordinator
     * re-applies the whole table after every snapshot restore (see MM's bracket
     * above). Re-placing the same item on the same host is a no-op, not a
     * duplicate and not a refusal.
     *
     * Called OUTSIDE the inner alternation loop — between rounds, and during a
     * round's teardown after `restore` and before `endQuery`.
     *
     * @return nonzero on success. Zero on a host the engine had itself offered
     *         as a candidate aborts the fill with
     *         RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED.
     */
    int (*place)(void* self, uint16_t hostCheck, SharedItem item);

    /**
     * Drop every placement this coordinator made, returning the engine's own
     * shuffled checks to unassigned. It must NOT touch the engine's graph, its
     * own restricted-pool placements, or anything the coordinator did not put
     * there.
     *
     * WHY THIS EXISTS, because it is the one call the audit's surface did not
     * have and it is not optional: the fill's dead-end recovery is a BATCH ROLL
     * BACK, and a roll-back that cleared only the coordinator's tables would
     * leave the previous attempt's placements inside both engines. The next
     * attempt would then see those hosts as assigned, run out of candidates, and
     * report a dead end that is an artefact of the retry rather than of the
     * world — turning one bad order into a permanently failing fill.
     *
     * Called from Combo_Logic_ResetPlacements(), hence at the start of every
     * fill attempt, and never inside a round.
     */
    void (*clearPlacements)(void* self);

    /**
     * End the round. Release whatever `beginQuery` set up and RESTORE THE
     * ENGINE'S COUPLING TO THE LIVE GAME — OoT re-points `Logic::mSaveContext`
     * at `&gSaveContext` here (audit §4.4). Called exactly once per round, last,
     * after `restore` and after the placement re-apply.
     */
    void (*endQuery)(void* self);

    /**
     * OPTIONAL PAIR — both NULL, or both non-NULL. Registration refuses one
     * without the other, because a snapshot with no restore silently corrupts
     * the save and a restore with no snapshot silently reverts to nothing.
     *
     * `snapshot` captures everything this engine's queries will mutate (MM:
     * `gSaveContext` whole, plus the game-event queue depth — audit §4.4);
     * `restore` puts it back. One pair brackets the whole round.
     *
     * @return `snapshot` returns nonzero on success; zero aborts the round with
     *         RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED. A failed snapshot must never
     *         be followed by queries — that is the whole point of the return.
     */
    int (*snapshot)(void* self);
    void (*restore)(void* self);
} ComboLogicEngine;

/**
 * Publish `engine` as the logic engine for `originGame`. Called once per game,
 * from that game's single-exe TU, or by a test for a stub.
 *
 * @param engine NULL UN-REGISTERS that game, so a test can install a stub and
 *               then restore the registry instead of leaving process-global
 *               state behind (the same courtesy
 *               `Combo_RegisterForeignItemPool(NULL, 0)` provides).
 * @return true if registered (or cleanly un-registered). False, with a logged
 *         reason and the registry UNCHANGED, when `originGame` is not a real
 *         game, `abiVersion` mismatches, a required pointer is NULL, or
 *         snapshot/restore are not both present or both absent.
 *
 * A second registration for the same game REPLACES the first and is logged:
 * two engines claiming one id-space is the ambiguity this surface exists to
 * prevent, so it must not pass silently.
 */
bool Combo_Logic_RegisterEngine(GameId originGame, const ComboLogicEngine* engine);

/** The registered engine for `originGame`, or NULL. Read-only. */
const ComboLogicEngine* Combo_Logic_GetEngine(GameId originGame);

// ============================================================================
// THE PLACEMENT TABLES
// ============================================================================
//
// TWO tables, keyed by HOST game, in PROCESS MEMORY ONLY. They are deliberately
// NOT in `gComboCtx`: the O7 boundary carve against `reserved[108]` is a later
// decision of epic #645, and a carve taken here would freeze a layout before
// the decision that sizes it. Nothing in this file is serialized, so nothing in
// this file is .redsave format.

/** One placement. RAM only; no offset here is format. */
typedef struct {
    uint16_t hostCheck; // in hostGame's own check id-space
    uint16_t itemClass; // the bag row's RSBS_ITEMCLASS_* bit, carried through
    SharedItem item;    // origin-tagged; may be either game's origin
} ComboLogicPlacement;

/**
 * Empty both tables AND tell each registered engine to drop the placements this
 * coordinator gave it (`clearPlacements`). Called at the start of every fill
 * attempt — that is the batch roll-back, and it is only a roll-back if both
 * sides forget. Also available to tests for isolation.
 */
void Combo_Logic_ResetPlacements(void);

/**
 * AUTHOR one placement directly: record it in the coordinator's table and hand
 * it to the owning host engine through `place`, exactly as the fill does.
 *
 * This is the entry a caller uses when the placement was DECIDED ELSEWHERE — the
 * locks author known-shape worlds with it, and the spoiler-LOAD path will need
 * precisely this shape to rebuild both tables from a spoiler's foreign section
 * without either game's header in scope (the inverse
 * `Combo_GetForeignItemByNameFor` already serves).
 *
 * IT PROVES NOTHING. Authoring bypasses the round, so it makes no reachability
 * claim about the host and no GOAL claim about the world; proof is
 * Combo_Logic_RunFill's exit condition and only ever that. A caller that means
 * "generate a world" must not build one out of these.
 *
 * @return false if `hostGame` is not a real game, the item carries no origin,
 *         the host is already assigned, the table is full, or the host engine is
 *         absent or refused. On false NOTHING was recorded.
 */
bool Combo_Logic_Place(GameId hostGame, uint16_t hostCheck, SharedItem item, uint16_t itemClass);

/** How many placements `hostGame` holds, or 0 for a non-game. */
int Combo_Logic_PlacementCount(GameId hostGame);

/** The `index`-th placement of `hostGame`, in insertion order (which is the
 *  fill's own order, so it is world-visible and stable). False out of range. */
bool Combo_Logic_PlacementAt(GameId hostGame, int index, ComboLogicPlacement* out);

/** The placement on (hostGame, hostCheck), or false if that host is unassigned.
 *  This is the coordinator's occupancy authority. */
bool Combo_Logic_GetPlacement(GameId hostGame, uint16_t hostCheck, ComboLogicPlacement* out);

/**
 * A stable FNV-1a digest over both tables in order (host game, host check,
 * origin, id, class). Two fills with the same digest placed identically.
 *
 * IT IS NOT A WORLD DIGEST and must never be presented as one: it covers this
 * coordinator's tables, not either game's own fill output, its spoiler, or any
 * `.redsave` byte. Its purpose is the same-seed / different-seed locks and
 * whatever the follow-on lanes need to compare two coordinator runs.
 */
uint32_t Combo_Logic_PlacementDigest(void);

// ============================================================================
// GOAL EVALUATION
// ============================================================================

/**
 * The GOAL expression over the two halves' own booleans (ADR 0010 D1 §1.1).
 *
 * @param goal an RSBS_COMBO_GOAL_* value (the FROZEN record's, never a CVar's)
 * @return 1 provable, 0 not, and -1 when this build has no evaluator for `goal`
 *         (RSBS_COMBO_GOAL_TRIFORCE_HUNT — answer O10's one shared piece count
 *         does not exist yet). A caller must distinguish -1 from 0.
 *
 * `beat-either` is a PLAIN OR and the coordinator never narrows it to an XOR:
 * an unbeatable half is permitted, both halves provable is a welcome outcome,
 * and nothing anywhere may bias toward asymmetry (ADR 0010 §1.2 / answer O1).
 */
int Combo_Logic_EvaluateGoal(uint8_t goal, int ootGoalReached, int mmGoalReached);

// ============================================================================
// ONE ROUND, EXPOSED
// ============================================================================

/** The assumed set / bag element: an origin-tagged item plus the class it was
 *  admitted under. The class is CARRIED, not filtered on — see the fill. */
typedef struct {
    SharedItem item;    // originGame must be GAME_OOT or GAME_MM
    uint16_t itemClass; // one RSBS_ITEMCLASS_* bit, or 0 when the caller has none
} ComboLogicBagItem;

typedef struct {
    const ComboLogicBagItem* assumed; // the assumed set A; NULL iff assumedCount == 0
    int assumedCount;
    uint8_t goal; // RSBS_COMBO_GOAL_*
} ComboLogicRoundRequest;

typedef struct {
    int status;     // RSBS_COMBO_LOGIC_*
    int iterations; // inner alternations actually run
    int crossingOpenOoT;
    int crossingOpenMM;
    int goalOoT;        // the OoT half's own answer
    int goalMM;         // the MM half's, AFTER the arrival gate
    int goalExpression; // GOAL(goalOoT, goalMM); -1 when the goal has no evaluator
    int candidatesOoT;  // reached, coordinator-unassigned hosts
    int candidatesMM;   // ditto, and zero while the arrival gate is closed
    int exchanged;      // crossing exchanges performed this round
    /** Was every host the coordinator has already placed on reached in this
     *  round? 1 yes, 0 no, and -1 when the round did not get far enough to
     *  evaluate it (an engine refusal or a malformed request). It is evaluated
     *  INSIDE the round because `checkReached` is only valid before teardown —
     *  which is why the `all-reachable` rung cannot be a post-pass. */
    int allHostsReached;
} ComboLogicRoundResult;

/**
 * Run ONE round and report what it saw, leaving the placement tables untouched.
 *
 * This is the coordinator's smallest observable unit and it is public for two
 * reasons beyond the locks: epic #645's first work item is measuring the cost
 * of one linked round against the #582 creation budget, and its second is
 * whether an assumed fill over MM's forward-authored graph converges — both are
 * questions about this function.
 *
 * @return the status, also written to `out->status` when `out` is non-NULL.
 */
int Combo_Logic_RunRound(const ComboLogicRoundRequest* req, ComboLogicRoundResult* out);

// ============================================================================
// THE SINGLE-BAG ASSUMED FILL
// ============================================================================

typedef struct {
    const ComboLogicBagItem* bag; // the union bag; NULL iff bagCount == 0
    int bagCount;
    uint8_t goal;      // RSBS_COMBO_GOAL_*  } both from the FROZEN record,
    uint8_t logicRung; // RSBS_COMBO_RUNG_*  } never from a live CVar
    /**
     * The coordinator's PRIVATE RNG seed, derived by the caller from the frozen
     * identity (`gComboCtx.sharedRandoSeed`, `comboSettingsHash`, ...). It is
     * never a game's RNG: both engines' RNGs belong to their own fills, a query
     * must consume none, and a coordinator that drew from either would couple
     * the world to the number of rounds the search happened to run.
     */
    uint32_t seed;
    /** Batch roll-backs within this seed; 0 means RSBS_COMBO_LOGIC_FILL_RETRIES.
     *  Re-rolling the SEED is the attempt ladder's job, one level up. */
    int maxAttempts;
} ComboLogicFillRequest;

typedef struct {
    int status;
    int attempts;         // attempts consumed, including the successful one
    int placed;           // placements in the tables on return
    int rounds;           // rounds run across every attempt
    bool goalProven;      // the exit condition was evaluated and held
    bool proofSkipped;    // rung `none`: no proof was attempted (goalProven is false)
    bool allHostsReached; // rung `all-reachable` only: every placed host was reached
    uint32_t placementDigest;
} ComboLogicFillResult;

/**
 * THE FILL. One bag, both games' hosts, the GOAL expression as the exit
 * condition (ADR 0010 D3/D4, increment 3).
 *
 * The algorithm, which is OoT's own assumed fill lifted one level (audit §4.3):
 * shuffle the bag with the private RNG; for each item, run a round with every
 * OTHER unplaced bag item assumed, take the union of both sides' candidate
 * hosts, pick one uniformly, and place it on its owning side. On an empty
 * candidate set, roll the whole batch back and retry with a different
 * deterministic order. When the bag is empty, run one final round with NOTHING
 * assumed and require the GOAL expression — that requirement is the loop's exit
 * condition, never a check bolted on after it.
 *
 * THE RUNGS ARE ONE CODE PATH with the exit condition parametrized, which is
 * ADR 0010 D5 read literally — the operator's "bag, then randomly distribute"
 * base mode is this same fill:
 *   RSBS_COMBO_RUNG_NONE          - the final round is SKIPPED. Placement still
 *                                   happens through the rounds (so a `none`
 *                                   world is still a legal single-bag world),
 *                                   but nothing is proved: `proofSkipped` is
 *                                   true and `goalProven` is false. A caller
 *                                   must not read "not proven" as "failed".
 *   RSBS_COMBO_RUNG_BEATABLE      - the GOAL expression must hold.
 *   RSBS_COMBO_RUNG_ALL_REACHABLE - the GOAL expression must hold AND every
 *                                   host the COMBO FILL placed on must be
 *                                   reached in that final round.
 *
 * The all-reachable rung's obligation is deliberately over PLACED hosts and not
 * over every location in either world. "Every location reachable" is each half's
 * own existing strictness axis (`RSK_ALL_LOCATIONS_REACHABLE` and MM's
 * analogue), which ADR 0010 §1.2 explicitly keeps per-half and composes with any
 * GOAL; the pair-level obligation this rung adds on top is that nothing the
 * SINGLE BAG distributed ended up somewhere the player cannot stand. Widening it
 * would also need a vtable call that enumerates every shuffled host, which no
 * consumer has asked for.
 *
 * DETERMINISM: the whole result is a pure function of (`bag` contents and
 * order, `goal`, `logicRung`, `seed`, `maxAttempts`, the two registered
 * engines). Same inputs, same placements, byte for byte.
 *
 * ON FAILURE the placement tables hold the LAST attempt's partial state; a
 * caller that means to discard them calls Combo_Logic_ResetPlacements().
 *
 * @return the status, also written to `out->status` when `out` is non-NULL.
 */
int Combo_Logic_RunFill(const ComboLogicFillRequest* req, ComboLogicFillResult* out);

// ============================================================================
// DELIBERATELY ABSENT — do not read these as oversights
// ============================================================================
//
//  - ANY PRODUCTION WIRING. No shipping TU registers an engine and no creation
//    seam calls the fill. The two engine implementations are two follow-on
//    lanes; until both exist a paired fill cannot run at all, which is why
//    Combo_Logic_RunFill refuses with one engine instead of half-filling.
//  - THE O7 BOUNDARY CARVE. The placement tables are RAM, not
//    `gComboCtx.reserved[108]`. Sizing the carve is epic #645 item 2.
//  - THE O8 CLASSIFICATION TABLE. `ComboLogicBagItem.itemClass` is carried
//    from the caller and recorded on the placement; the coordinator filters
//    nothing by it. When the single-owner table lands in
//    `src/common/shared_items.*` (answer O8) the class is read from there
//    instead, and any narrowing belongs to the pool DRAW
//    (`Combo_ForeignPoolDrawFor`) which already runs before the bag exists —
//    the six membership criteria run FIRST and the bitset selects among the
//    survivors (ADR 0011 decision 3.1), an ordering this file may not weaken.
//  - THE O10 SHARED TRIFORCE COUNT, hence triforce-hunt refusing with
//    RSBS_COMBO_LOGIC_ERR_UNSUPPORTED_GOAL rather than being evaluated wrong.
//  - THE SPOILER. One artifact for the pair is #564 V23 / audit P11; this
//    coordinator exposes its tables and stops there.
//  - THE ATTEMPT LADDER. Re-rolling the seed on a failed fill is the layer
//    above; the coordinator's retries are batch roll-backs within ONE seed.
//  - PER-GAME PASSES. OoT's restricted-pool fills and both games' junk
//    `FastFill`s stay per-game and are not this bag (audit amendment 2).
//  - THE CROSSING EDGE'S TIME-OF-DAY TERMS (answer O2's Day-1 re-stamp and
//    reset-time guard). Those are authored inside the engines, behind
//    `crossingOpen`; the coordinator only reads the resulting fact.

#ifdef __cplusplus
}
#endif

#endif // RSBS_COMMON_COMBO_LOGIC_H
