/**
 * @file combo_logic.h
 * @brief The combo-logic coordinator and the engine query surface it drives
 *        (ADR 0010 increment 3, #645; O4 = COMPOSITION, operator 2026-09-17).
 *
 * ============================================================================
 * WHAT THIS IS, AND WHAT IT IS NOT
 * ============================================================================
 *
 * ADR 0010 answer O4 is ruled COMPOSITION: both ports' solvers stay
 * authoritative in their own dialects, and a game-header-free coordinator in
 * `src/common` owns exactly three things — the union bag of origin-tagged
 * items, the two origin-keyed placement tables, and the round loop. It never
 * evaluates a guard, never names an `RG_*` / `RI_*` / `RR_*` / `RC_*`, and
 * never touches a save. Everything that requires a game's enum in scope lives
 * behind the `ComboLogicEngine` vtable below, implemented in that game's own
 * single-exe TU beside its foreign-items TU.
 *
 * NOTHING HERE IS WIRED INTO A PRODUCTION PATH. No engine is registered by any
 * shipping TU at this commit; no creation seam calls the fill; no world is
 * generated by this code. It is the coordinator core plus its contract, locked
 * over synthetic stub engines in `src/common/tests/test_combo_logic.c`. The
 * deliberate absences are listed at the bottom of this header — read that list
 * before concluding something is missing by accident.
 *
 * ============================================================================
 * WHY A REGISTERED VTABLE AND NOT FIXED `extern "C"` SYMBOLS
 * ============================================================================
 *
 * The solver-inventory audit (§4.1) sketched the surface as two sets of fixed
 * C symbols (`OoT_Logic_Expand`, `MM_Logic_Expand`, ...). A REGISTERED VTABLE
 * IS REQUIRED INSTEAD, for one reason that decides it:
 *
 *   A ROM-free, display-free test must be able to drive the whole coordinator
 *   over engines it authors itself.
 *
 * Fixed symbols cannot be substituted: the real engines' TUs link into the same
 * binary as the tests (this is a single executable), so a test cannot provide
 * its own `OoT_Logic_Expand` without a duplicate-symbol error, and a test that
 * drove the REAL engines would need both ROMs, both graphs built, a display for
 * MM's crawl (audit §6.3), and a generated world — which is precisely the
 * dependency chain that has kept every pair-level assertion in this project
 * vacuous. With a vtable, `test_combo_logic.c` registers two small stub engines
 * whose reachability is a bitmask, and every claim below is falsifiable on the
 * `redship` tier in milliseconds.
 *
 * Two smaller reasons, both real: a build with only one game's engine TU linked
 * resolves cleanly (the missing origin simply has no engine, the same property
 * `Combo_RegisterForeignItemPool` exists for), and MM's snapshot/restore pair is
 * OPTIONAL, which a fixed-symbol surface can only express as a stub that lies.
 *
 * The cost is one indirect call per query, against an engine call that runs a
 * whole reachability search. It is not measurable.
 *
 * ============================================================================
 * THE BOUNDARY (ADR 0002)
 * ============================================================================
 *
 * Only game-neutral scalars cross: a `SharedItem` (origin tag + id), a HOST
 * CHECK ID, and the HOST'S ORIGIN GAME. Nothing else. `assumeOwnItem` and the
 * own-origin half of `place` receive ONLY ids from the receiving engine's own
 * id-space, because the coordinator routes by `item.originGame` before calling —
 * so ADR 0002 holds by construction, not by review. MM reports "check 201
 * reached"; the coordinator looks up `placement[MM][201] == SharedItem{OOT, id}`
 * and calls the OoT engine's `assumeOwnItem(id)`. No MM code ever sees that id.
 *
 * Host check ids live in each game's own check id-space and are never compared
 * across games: `(hostGame, hostCheck)` is the key, exactly as `(originGame,
 * name)` is the key in foreign_items.h for the same #356 reason.
 */

#ifndef RSBS_COMMON_COMBO_LOGIC_H
#define RSBS_COMMON_COMBO_LOGIC_H

#include "context.h"       // SharedItem, GameId
#include "foreign_items.h" // RSBS_COMBO_GOAL_*, RSBS_COMBO_RUNG_*, RSBS_ITEMCLASS_*

#ifdef __cplusplus
extern "C" {
#endif

/** Bumped when the vtable's shape or any call's contract changes. An engine
 *  registering a different value is REFUSED rather than called through — a
 *  half-updated engine would otherwise be diagnosed as a logic bug months
 *  later. This is a build-internal number: nothing here is serialized, so it is
 *  not .redsave format and carries no append-only obligation.
 *
 *  3 (2026-09-26, the MULTIPLICITY ruling): the vtable's SHAPE is unchanged, but
 *  `assumeOwnItem`'s MEANING is not — one call is now one COPY, and an engine
 *  must count it (see that entry). An ABI-2 engine de-duplicated by id, which is
 *  exactly the behaviour this contract now forbids, so the number moves even
 *  though no pointer did.
 *
 *  4 (2026-09-27, ADR 0010 answer O10): the vtable's SHAPE grows by one trailing
 *  OPTIONAL entry, `triforcePieces`, the engine-neutral piece query the
 *  triforce-hunt goal reads. Every ABI-3 meaning is unchanged; an engine that
 *  leaves the entry NULL registers as before and simply cannot answer a
 *  triforce-hunt fill (refused with RSBS_COMBO_LOGIC_ERR_UNSUPPORTED_GOAL). */
#define RSBS_COMBO_LOGIC_ENGINE_ABI 4u

// ============================================================================
// Status codes — DIAGNOSTICS, NOT FORMAT
// ============================================================================
//
// Nothing in this header is serialized, so these values may be renumbered
// freely (unlike every value space in foreign_items.h). Combo_Logic_StatusName
// renders them; the fill and round results carry them.

#define RSBS_COMBO_LOGIC_OK 0
/** One or both engines are not registered. A paired fill requires BOTH: the
 *  combo is one game (one-game semantics), so a fill with one half missing
 *  would author a world whose other half was never decided. */
#define RSBS_COMBO_LOGIC_ERR_NO_ENGINE 1
/** Malformed request: NULL where a pointer is required, a negative count, an
 *  unpinned rung value, a bag item tagged GAME_NONE. */
#define RSBS_COMBO_LOGIC_ERR_BAD_REQUEST 2
/** The GOAL value cannot be evaluated by THIS pair of engines: an unpinned GOAL
 *  value, or RSBS_COMBO_GOAL_TRIFORCE_HUNT over an engine that does not supply
 *  the `triforcePieces` query ADR 0010 answer O10's one shared count is read
 *  through. Refused loudly rather than silently evaluated as beat-both, which
 *  would ship a world whose stated goal is not the goal that was proved. */
#define RSBS_COMBO_LOGIC_ERR_UNSUPPORTED_GOAL 3
/** An engine's reachability is not monotone: an observable that may only grow
 *  within a round (its candidate-host count, or its crossing flag) DECREASED.
 *  Assumed fill and the trailing no-logic dump are unsound without monotonicity
 *  (ADR 0010 §2.3), so this is refused, never worked around. */
#define RSBS_COMBO_LOGIC_ERR_NON_MONOTONE 4
/** The round loop hit RSBS_COMBO_LOGIC_MAX_ROUND_ITERATIONS without an engine
 *  reporting "nothing new". Either an engine reports `changed` unconditionally,
 *  or the graph is far larger than the cap anticipates. Reported, never looped
 *  on — see the termination argument at the loop in combo_logic.c. */
#define RSBS_COMBO_LOGIC_ERR_NO_FIXPOINT 5
/** Dead end: an item had to be placed and no reached, unassigned host existed
 *  on either side, on every attempt. This is the failure the ATTEMPT LADDER
 *  above the coordinator answers with a deterministic re-roll (ADR 0010 §2.3);
 *  the coordinator's own retries are the batch roll-back inside one seed.
 *
 *  Under RSBS_COMBO_RUNG_NONE it cannot mean that: that rung runs no round and
 *  draws from ALL empty hosts, so the only way it can exhaust them is that both
 *  worlds together hold fewer free hosts than the bag holds items. That is a
 *  capacity fact about the pools, not a logic fact about the world, and no
 *  re-roll can fix it. */
#define RSBS_COMBO_LOGIC_ERR_NO_CANDIDATE 6
/** Every attempt placed the whole bag, and on none of them was the GOAL
 *  expression provable with the bag empty. The GOAL check is the fill's EXIT
 *  CONDITION (ADR 0010 D4), so this is a fill failure, not a warning. */
#define RSBS_COMBO_LOGIC_ERR_GOAL_UNPROVABLE 7
/** Under RSBS_COMBO_RUNG_ALL_REACHABLE only: the GOAL was provable but some
 *  placed host was not reached in the final round. */
#define RSBS_COMBO_LOGIC_ERR_NOT_ALL_REACHED 8
/** A fixed capacity was exceeded: the bag size (RSBS_COMBO_LOGIC_BAG_CAP),
 *  placements on one host game (RSBS_COMBO_LOGIC_PLACEMENT_CAP), or the hosts one
 *  engine offered in ONE enumeration (RSBS_COMBO_LOGIC_HOST_CAP). Those are three
 *  different quantities and are sized separately — see the capacity block. */
#define RSBS_COMBO_LOGIC_ERR_CAPACITY 9
/** An engine refused a call it is contractually required to satisfy —
 *  `beginQuery` or `snapshot` returned 0, or `place` returned 0 for a host the
 *  engine had itself offered as a candidate. */
#define RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED 10

/** Its name ("ok", "no-engine", ...), or "(unknown)". Never NULL. */
const char* Combo_Logic_StatusName(int status);

// ============================================================================
// Fixed capacities
// ============================================================================

/** Bag items in one fill. The union bag is both games' last general ADVANCEMENT
 *  pass only (audit amendment 2) — OoT's remaining-advancement set plus MM's
 *  shuffled pool — so the real figure is low hundreds. */
#define RSBS_COMBO_LOGIC_BAG_CAP 512
/** Placements per HOST game. RAM only: see the placement-table note below. It
 *  bounds what one side can RECEIVE out of the bag, so it is sized against the
 *  bag (above) and NOT against either game's check pool. */
#define RSBS_COMBO_LOGIC_PLACEMENT_CAP 1024
/**
 * Hosts one engine may OFFER in ONE enumeration — `reachedEmptyHosts` and
 * `allEmptyHosts`. IT IS A DIFFERENT QUANTITY FROM RSBS_COMBO_LOGIC_PLACEMENT_CAP
 * and it is the one the collector's scratch must be sized by, which is the
 * distinction increment 3 got wrong (it sized the scratch by the placement cap,
 * so the first honest engine would have aborted the first fill on the first bag
 * item with ERR_CAPACITY, for a reason with nothing to do with the world).
 *
 * The bound is A GAME'S CHECK ID-SPACE, not the bag: an engine enumerating "every
 * shuffled check I do not consider assigned" answers with its whole pool. Measured
 * today: OoT's `RandomizerCheck` has 2528 enumerators up to and including `RC_MAX`
 * and MM's has 2258, neither with an explicit initialiser, so the two id-spaces
 * are 0..2527 and 0..2257. 4096 carries either side whole with better than half
 * again of headroom, and both ports may add checks without anyone re-deriving this
 * number.
 *
 * Exceeding it is still REFUSED (RSBS_COMBO_LOGIC_ERR_CAPACITY) and never
 * truncated: a truncated candidate list would silently narrow the world to a
 * prefix of one engine's table, which no determinism row could see. The refusal
 * names this constant, so the fix when a port outgrows it is to raise this line.
 */
#define RSBS_COMBO_LOGIC_HOST_CAP 4096
#if RSBS_COMBO_LOGIC_HOST_CAP < RSBS_COMBO_LOGIC_PLACEMENT_CAP
#error "RSBS_COMBO_LOGIC_HOST_CAP must be at least the placement cap: every placed host was first an offered host"
#endif
/** Watchdog bound on one round's inner alternations. NOT the termination
 *  argument — convergence follows from monotonicity over a finite lattice; this
 *  bound exists to turn a VIOLATED premise into a diagnosis instead of a hang.
 *  The audit expects real convergence in two or three alternations (§4.3). */
#define RSBS_COMBO_LOGIC_MAX_ROUND_ITERATIONS 256
/** Default batch roll-backs within one seed before the fill gives up, mirroring
 *  OoT's own assumed-fill retry discipline (`fill.cpp:877-934`). The ATTEMPT
 *  LADDER above the coordinator is a different mechanism: it re-rolls the SEED.
 *  Conflating the two produced the silent-vanilla-revert bug class (ADR 0010
 *  §2.2), so they are named separately here. */
#define RSBS_COMBO_LOGIC_FILL_RETRIES 10

// ============================================================================
// THE ENGINE SURFACE
// ============================================================================
//
// ---------------------------------------------------------------------------
// WHO OWNS WHAT
// ---------------------------------------------------------------------------
//
// THE COORDINATOR owns: the union bag, both placement tables, the round loop,
// the assumed set, the RNG, the GOAL/rung evaluation, and the decision of WHEN
// an item counts as held. It owns occupancy: its table is the single authority
// on "is this host already assigned".
//
// AN ENGINE owns: its own region graph, its own condition dialect, its own
// simulated inventory, and its own save coupling. It answers questions about
// its own world and nothing else. It never inspects the coordinator's tables,
// never asks about the other game, and never decides anything about the fill.
//
// AN ENGINE MUST LEAVE UNTOUCHED, across a whole round:
//   - the player's live save, except through the snapshot/restore pair it
//     itself declares (see MM's bracket below);
//   - any RNG the world generation consumes. A query runs a VARIABLE number of
//     times per fill, so an engine that drew one random number inside a query
//     would make the world a function of the search's shape. The coordinator's
//     own RNG is private and seeded from the frozen identity (below).
//   - global state the OTHER engine reads. The two engines share a process;
//     they must not share state.
//
// ---------------------------------------------------------------------------
// CALL ORDER — THE ROUND
// ---------------------------------------------------------------------------
//
// One ROUND is one complete reachability evaluation under a partial placement P
// (the coordinator's tables) and an assumed set A (bag items not yet placed).
// The coordinator runs a round per bag item, plus one final round with A empty.
// Exactly this sequence, per round, for both engines:
//
//   for each side S in {OOT, MM}:            // OoT first, deterministically
//       if (S.snapshot) S.snapshot()         // BEFORE beginQuery: the restore
//       S.beginQuery()                       //   must undo beginQuery too
//   for each a in A:  side(a.originGame).assumeOwnItem(a.id)   // one call per COPY
//   repeat, bounded by RSBS_COMBO_LOGIC_MAX_ROUND_ITERATIONS:
//       changed  = OOT.expand()
//       changed |= exchange OoT-hosted, MM-origin items    // gated, below
//       changed |= MM.expand()
//       changed |= exchange MM-hosted, OoT-origin items    // gated, below
//   until !changed
//   read: crossingOpen, goalReached, reachedEmptyHosts, checkReached
//   for each side S, in reverse:
//       if (S snapshotted) { S.restore(); re-apply all of P[S] through S.place() }
//       if (S.beginQuery was CALLED)  S.endQuery()
//
// The re-apply runs ONLY for a side that restored. A side with no snapshot never
// lost anything, so re-placing there would be pure cost — and the cost is not
// small: it is one `place` per placement per round, and the fill runs a round
// per bag item.
//
// THE BRACKET'S OWNERSHIP RULE, when a round is abandoned part-opened. A round
// can fail while the two sides are being opened — `snapshot` refuses, or
// `beginQuery` refuses — and the teardown above then runs over a bracket that is
// only half there. Exactly one rule decides it, and it is per CALL, not per
// success:
//
//   * `restore` is called iff `snapshot` was called AND RETURNED NONZERO. There is
//     nothing to put back otherwise, and a restore over a blob that was never
//     captured would write stale bytes over live state.
//   * `endQuery` is called iff `beginQuery` WAS CALLED AT ALL — including when it
//     returned zero. The engine's detach lives in `beginQuery` and its only
//     documented inverse lives in `endQuery` (`Logic::mSaveContext` for OoT), so
//     a `beginQuery` that detaches and then refuses would otherwise leave the
//     engine coupled to a simulated save for the rest of the process. That was
//     increment 3's behaviour and it is the audit §1.8 hazard exactly.
//   * A side whose `snapshot` refused is never asked to begin, and therefore gets
//     neither `endQuery` nor `restore`. Sides opened BEFORE the refusing one are
//     torn down in full.
//
// WHAT AN ENGINE MUST THEREFORE TOLERATE, stated as the two teardowns a
// part-opened side can actually receive:
//
//   * WITHOUT a snapshot pair: `endQuery` on a round that never opened. It must be
//     a no-op there, not an unwind of state the engine never set — a flag tested at
//     the top is the whole of it.
//   * WITH a snapshot pair, when `snapshot` succeeded and `beginQuery` then
//     refused: `restore`, THEN A FULL RE-APPLY OF THAT SIDE'S WHOLE PLACEMENT TABLE
//     THROUGH `place`, then `endQuery` — all three on an engine whose `beginQuery`
//     returned zero. So `restore` and `place` must both be callable outside an open
//     query bracket, and `place` must still be idempotent there. This is the shape
//     MM meets, because MM is the side that snapshots.
//
// Refusing in `beginQuery` BEFORE mutating anything is what makes both trivially
// true, and it is the shape both engines take.
//
// RSBS_COMBO_RUNG_NONE RUNS NO ROUND AT ALL. Under that rung the only engine
// calls are `clearPlacements` (the reset), `allEmptyHosts` and `place` — no
// bracket is opened, nothing is assumed, nothing is expanded. See the rung list
// at Combo_Logic_RunFill.
//
// THE EXCHANGE GATES, stated as the travel they model (audit §4.5):
//   - An MM-origin item sitting in an OoT host reaches MM iff that host is
//     reached AND OoT's crossing is open (the player must be able to get to
//     MM to spend it).
//   - An OoT-origin item sitting in an MM host reaches OoT iff that host is
//     reached AND OoT's crossing is open (to get there at all) AND MM's
//     crossing is open (to get back).
//
// THE ARRIVAL GATE — a coordinator rule the audit did not state, taken here
// deliberately. The combo's file starts in OoT and MM is reached through the
// crossing, but MM's engine knows nothing about that: its graph root is
// reachable unconditionally in its own dialect (audit §4.5). So the coordinator
// applies the gate the MM engine cannot: while OoT's crossing is CLOSED, MM's
// hosts are not candidates and MM's goal does not count as reached. Without it,
// a world whose crossing never opens would host progression in a Termina the
// player can never enter, and `beat-either` would call that half proved. In
// practice OoT's crossing opens at sphere zero under default settings, which is
// exactly why this must be a rule rather than an observation.
//
// ---------------------------------------------------------------------------
// MM'S BRACKET (audit §4.4 / amendment 1)
// ---------------------------------------------------------------------------
//
// Every MM query, the "read-only" crawl included, writes MM's LIVE save. So one
// snapshot/restore brackets the WHOLE round, not each call, and the
// coordinator re-applies the side's whole placement table after the restore.
//
// It re-applies ALL of P[S], not only the placements made during the round,
// because that invariant holds no matter when the snapshot was taken: after
// every round, a restoring engine's state contains every placement the
// coordinator has decided. This is what makes `place` IDEMPOTENT a hard
// requirement rather than a nicety (see `place` below). The narrower reading —
// re-apply only what this round placed — is the same set in the fill's own
// shape, because the fill places BETWEEN rounds and never inside the bracket;
// re-applying the whole table is the reading that stays correct if a later
// consumer ever does place inside one.
//
// An engine whose queries are genuinely pure supplies NULL for both. OoT's is:
// `Logic::Reset(true)` detaches the save and the search runs against the
// detached copy (audit §4.2). OoT's one obligation is the inverse — re-point
// `Logic::mSaveContext` at the live save in `endQuery`, or the next in-game
// progressive give resolves against a stale simulated save (audit §1.8).

/**
 * One engine. Every function pointer except `snapshot`/`restore` and the
 * trailing optional `triforcePieces` (ABI 4) is REQUIRED;
 * registration refuses a vtable with a hole rather than crashing at the first
 * round. `self` is passed to every call and is the engine's own opaque state —
 * NULL is legal and is what a real engine (whose state is file-static in its
 * own TU) passes. It exists so a test can register two stub engines that share
 * one set of function pointers.
 */
typedef struct ComboLogicEngine {
    /** Must equal RSBS_COMBO_LOGIC_ENGINE_ABI. */
    uint32_t abiVersion;
    /** Opaque engine state, passed to every call below. May be NULL. */
    void* self;

    /**
     * Begin one round. Reset the simulated inventory to the WORLD'S STARTING
     * INVENTORY and detach from anything this engine must not mutate.
     *
     * CALLED EXACTLY ONCE PER ROUND, before any other call of that round.
     *
     * THIS IS THE CALL THE OoT ENGINE CANNOT SKIP. `ReachabilitySearch` does
     * NOT reset OoT's `logic` singleton: a search run without
     * `Logic::Reset(true)` first INHERITS the previous search's simulated
     * inventory, and since the coordinator runs one round per bag item, that
     * would make every round after the first answer a question about a world
     * holding strictly more items than the round was asked about. The failure is
     * silent and it looks like the fill working.
     *
     * @return nonzero on success. Zero aborts the round with
     *         RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED.
     *
     * `endQuery` IS STILL CALLED WHEN THIS RETURNS ZERO (the ownership rule in
     * the CALL ORDER block above). So an engine has two ways to be correct and
     * must pick one: refuse BEFORE touching anything — the recommended shape,
     * since a validation-only failure needs no inverse — or make `endQuery`
     * unwind whatever the partial open left behind. What it must NOT do is
     * detach, refuse, and expect nobody to notice.
     *
     * WHOSE JOB THE STARTING STATE IS. "The world's starting inventory" is the
     * inventory the frozen profile starts the player with at FILE CREATION —
     * never whatever a live save happens to hold. There are exactly two engine
     * shapes, and the contract assigns the job differently for each:
     *
     *   - AN ENGINE WITH A DETACHED SIMULATED SAVE (OoT: `Logic::Reset(true)`
     *     allocates one) re-derives the starting state ITSELF, from the frozen
     *     settings, on every round. The live save is irrelevant to its answer.
     *   - AN ENGINE WITH NO DETACHED SAVE (MM: its world state IS `gSaveContext`,
     *     every guard reads it, and there is no reset primitive) cannot re-derive
     *     anything. Its round starts from the live save AS SNAPSHOTTED, so THE
     *     CALLER OF Combo_Logic_RunRound / Combo_Logic_RunFill OWNS putting that
     *     save in the file-creation starting state first (for MM: a fresh
     *     `MM_Sram_InitNewSave`, the frozen profile resolved, and
     *     `Rando::GrantStartingItems` — the state the creation seam leaves, which
     *     `MM_ComboLogic_ApplyShippedProfile` reproduces for the measurement).
     *     Opening a round on a mid-game MM save is a caller defect: the round
     *     would silently assume every item the player already collected. The
     *     engine cannot detect it, so the contract puts it on the caller.
     *
     * Either way, what `beginQuery` resets is the ROUND's own accumulation — the
     * copies granted, the hosts harvested, the reached sets — and it resets all
     * of it, because the coordinator re-seeds every copy it means the round to
     * hold (see `assumeOwnItem`).
     */
    int (*beginQuery)(void* self);

    /**
     * Grant one of THIS ENGINE'S OWN items into the simulated inventory — the
     * assumed-fill "pretend the player has it". `ownItemId` is always from this
     * engine's own id-space; the coordinator routed by origin before calling.
     *
     * "OWN ITEM" MEANS: an id this engine's own enum names, whose effect this
     * engine's own give path applies. It does NOT mean "an item found in this
     * game" — an MM-origin item found in an OoT chest is granted to the MM
     * engine, because MM is where that id means something.
     *
     * ONE CALL IS ONE COPY (ABI 3, the operator's multiplicity ruling of
     * 2026-09-26). The bag holds one row per copy, and within one round the
     * coordinator calls this EXACTLY ONCE for every copy the round is meant to
     * hold, from exactly two sources and never a third:
     *
     *   1. SEEDING — once per row of the assumed set, in the assumed set's order
     *      (the fill's own shuffled order of the not-yet-placed rows);
     *   2. EXCHANGE — once per foreign-origin PLACEMENT whose host became
     *      reachable across an open crossing, in host-table insertion order. A
     *      placement is delivered at most once per round (the coordinator keeps
     *      a per-round delivered bit per placement), so a later alternation
     *      never re-delivers a copy it already handed over.
     *
     * A row is either assumed or placed, never both, so no copy reaches this
     * call twice. The same ID reaching it twice therefore means TWO COPIES —
     * two small keys, two progressive-strength tiers — and the engine MUST
     * COUNT BOTH. De-duplicating by id (what ABI-2 engines did) makes a round
     * evaluate a world in which the player holds one of each, which is the
     * measured reason no real world could be PROVED under ABI 2 (#645, the
     * 2026-09-22 measurement: 321 OoT bag rows were only 105 distinct ids).
     *
     * WHAT A REPEAT MEANS, per item shape — each engine's give path decides, and
     * each engine must make every shape exact:
     *   - a SET item (a mask, a song, a medallion): the second copy is inert.
     *     Harmless, and correct.
     *   - a PROGRESSIVE item: the next tier, CLAMPED AT THE ITEM'S TOP TIER. A
     *     copy past the top (a plentiful surplus, or a starting item plus its
     *     pool copies) must leave the inventory exactly at the top tier — never
     *     wrap, never walk into a neighbouring field, never lower anything.
     *   - a COUNTER item (small keys, stray fairies, tokens, triforce pieces,
     *     heart pieces, beans): +1, CLAMPED AT THE COUNTER'S MAXIMUM, so a
     *     surplus copy can neither overflow the counter's storage nor claim a
     *     count the game's own world does not contain. EVERY engine clamps its
     *     counters, and none may rest an exemption on "no bag is that big": a
     *     round has no bag cap (Combo_Logic_RunRound takes an assumed set of any
     *     size, and combo-logic-measure's M2b assumes 2489 rows in one), and the
     *     ports' counters are narrow — OoT's small keys are an `s8` read back
     *     through a `-1` sentinel, so its 255th key copy reads as ZERO keys. The
     *     maximum must be derived from the game's own data or the seed's
     *     settings, and must be at least the largest count any of that game's
     *     logic terms asks for, so the clamp can never lower an answer. A copy
     *     at the maximum is absorbed; the clamp never lowers a count either.
     *
     * ORDER-INDEPENDENT: the round's answer must be a function of the MULTISET
     * of copies granted, not of their order. This is NOT automatic: OoT's
     * unclamped progressive arithmetic is order-DEPENDENT (a wallet copy past the
     * top carries into the bullet bag's field, so [slingshot, wallet x5] and
     * [wallet x5, slingshot] end in different inventories). With the clamps
     * above, each progressive and counter row reads and writes only its own tier
     * or count, which is what makes it true of both real engines — locked over
     * both, with OoT's red half observed, by combo-logic-multiplicity (P). An
     * engine for which it is not true must canonicalise.
     *
     * It is called BETWEEN `expand()` calls, so it must not invalidate whatever
     * `expand` accumulated — it may only ADD. NOTHING EVER REMOVES A COPY WITHIN
     * A ROUND: the coordinator has no "un-assume" call, the assumed set is seeded
     * once before the first `expand`, and an exchange only ever delivers. So an
     * engine's per-round grant record may be append-only, and must be — each
     * engine TU states how its record guarantees it.
     *
     * It must never REDUCE reachability. An engine whose give path can lower a
     * capacity, consume a resource or clear a flag breaks monotonicity, and
     * with it the soundness of the whole fill (ADR 0010 §2.3). The top-tier and
     * maximum clamps above exist precisely because the unclamped give paths CAN
     * lower a capacity once copies outnumber tiers or the counter's storage
     * (OoT's wallet: a fourth upgrade copy wraps its two-bit field to zero; OoT's
     * small keys: the 255th copy reads as zero keys).
     */
    void (*assumeOwnItem)(void* self, uint16_t ownItemId);

    /**
     * One reachability expansion over this engine's own graph, under everything
     * granted so far this round.
     *
     * @return nonzero iff something became reachable that was not reachable at
     *         the previous `expand()` of this round (a region, a check, the
     *         crossing). Returning nonzero forever is a contract violation; the
     *         coordinator's watchdog reports it as
     *         RSBS_COMBO_LOGIC_ERR_NO_FIXPOINT rather than spinning.
     *
     * Called repeatedly until the coordinator sees no side change. It must be
     * safe to call with nothing new granted (answer: zero, cheaply).
     *
     * THE OWN-ORIGIN HARVEST IS PER PLACED HOST, NOT PER ID. When a host holding
     * one of this engine's OWN items (a coordinator placement with this game's
     * origin) becomes reached, `expand` grants that item — ONCE PER HOST PER
     * ROUND. Two hosts holding the same id are two copies and both are granted;
     * one host is never granted twice however many alternations the round runs.
     * The grant obeys the same clamps as `assumeOwnItem`.
     */
    int (*expand)(void* self);

    /**
     * Is the cross-game crossing reachable right now, from THIS engine's side?
     * OoT: `RegionTable(RR_MARKET_MASK_SHOP)->Child()`. MM:
     * `RR_CLOCK_TOWER_INTERIOR` in the reachable set. A region FACT, not a new
     * graph edge — neither port's region files change for increment 3 (audit
     * amendment 3). Pure read; never mutates.
     */
    int (*crossingOpen)(void* self);

    /**
     * Is `hostCheck` — an id in THIS engine's own check id-space — reached
     * right now? Pure read. The coordinator asks only about hosts this engine
     * itself reported or was given via `place`.
     */
    int (*checkReached)(void* self, uint16_t hostCheck);

    /**
     * The engine's candidate hosts: shuffled checks it owns that are REACHED
     * right now and that it does not consider already assigned.
     *
     * ORDER IS A CONTRACT. The list must be in a STABLE order that is a
     * function of the engine's graph alone — ascending check id, or fixed table
     * order — and NOT of the order items were granted this round. The
     * coordinator picks a host from this list with its own RNG, so an order
     * that depended on grant order would make the world depend on the search's
     * shape instead of on the seed, and the determinism rows would catch it only
     * sometimes.
     *
     * @param out NULL to count only (then `cap` is ignored).
     * @param cap capacity of `out`; at most `cap` ids are written.
     * @return the TOTAL number of candidate hosts, which may EXCEED `cap`. The
     *         return is the total in both the count-only and the write case, so
     *         the coordinator can tell truncation from exhaustion.
     *
     * The coordinator filters the result against its OWN tables before using
     * it, so an engine that over-reports (offering a host the coordinator has
     * already filled) costs nothing, and one that under-reports merely narrows
     * its own world. Occupancy has exactly one authority and it is not here.
     */
    int (*reachedEmptyHosts)(void* self, uint16_t* out, int cap);

    /**
     * EVERY host this engine owns that it does not consider already assigned —
     * the same list as `reachedEmptyHosts` WITHOUT the reachability filter.
     *
     * THIS IS THE `none` RUNG'S HOST SOURCE and it is the reason the call
     * exists. Audit §4.3 says that under RSBS_COMBO_RUNG_NONE "the round is
     * skipped and hosts are drawn from all empties" — the operator's "bag, then
     * randomly distribute" base mode. Drawing from `reachedEmptyHosts` instead
     * would make the no-logic rung reachability-gated: it could refuse a world
     * with ERR_NO_CANDIDATE although a free host existed, and it would pay a
     * full reachability round per bag item for an answer it then throws away.
     *
     * CALLED OUTSIDE ANY ROUND. There is no `beginQuery` in force when the
     * coordinator calls this, so it must NOT consult the simulated inventory,
     * the reached set, or anything else a round sets up. It is a pure
     * enumeration of the engine's own shuffled-check table minus the hosts it
     * already holds — the same shape as asking a pool what is still in it.
     *
     * ORDER IS A CONTRACT, for the same reason as `reachedEmptyHosts`: a
     * STABLE order that is a function of the engine's own table alone.
     *
     * @param out NULL to count only (then `cap` is ignored).
     * @param cap capacity of `out`; at most `cap` ids are written.
     * @return the TOTAL, which may EXCEED `cap`, in both the count-only and the
     *         write case — truncation must be distinguishable from exhaustion.
     *
     * The coordinator filters the result against its own tables, so this must
     * be a SUPERSET of `reachedEmptyHosts`'s list and over-reporting is free.
     */
    int (*allEmptyHosts)(void* self, uint16_t* out, int cap);

    /**
     * Is THIS HALF'S goal reached right now? OoT: `RG_TRIFORCE` reached, i.e.
     * `CheckBeatable`'s condition. MM: Majora's Lair reached and Majora
     * defeated, through MM's own authored gate chain (ADR 0010 D1/D2).
     *
     * ONE HALF'S ANSWER ONLY. The coordinator composes the two under the frozen
     * GOAL value; an engine must never try to answer for the pair, and must
     * never widen its own half because the other half is unprovable (the OR is
     * never narrowed to an XOR — ADR 0010 §1.2).
     */
    int (*goalReached)(void* self);

    /**
     * Record that `hostCheck` — a host in THIS engine's check id-space — holds
     * `item`, which may be of EITHER origin.
     *
     *   - `item.originGame` == this engine's game: a real placement (OoT:
     *     `PlaceItemInLocation`; MM: the `RANDO_SAVE_CHECKS` write).
     *   - `item.originGame` == the other game: a JUNK COVER. The host's own
     *     table gets a legal local junk item and the foreign identity stays in
     *     the coordinator's table. A raw foreign id must never enter this
     *     engine's tables (ADR 0002).
     *
     * IT MUST NOT GRANT THE ITEM. Placing is not holding: the coordinator
     * decides when an item counts as held (`assumeOwnItem`, and the harvest of
     * own-origin items that `expand` does when their host becomes reached). An
     * engine that granted on place would make every placement instantly
     * available and the proof vacuous.
     *
     * IT MUST BE IDEMPOTENT for the same (hostCheck, item): the coordinator
     * re-applies the whole table after every snapshot restore (see MM's bracket
     * above). Re-placing the same item on the same host is a no-op, not a
     * duplicate and not a refusal.
     *
     * Called OUTSIDE the inner alternation loop — between rounds, and during a
     * round's teardown after `restore` and before `endQuery`.
     *
     * WHAT `place` MAY AND MAY NOT DO, stated as a list because an implementer
     * guessing wrong here is invisible to every determinism row:
     *   MAY   - write THIS host's own table entry (the item, or the junk cover);
     *   MAY   - record what the host held before, so `clearPlacements` can put
     *           it back;
     *   MUST NOT grant the item, in the player's save OR in any simulated state
     *           a later search reads (OoT: `Logic::inLogic[]` as well as the
     *           save context);
     *   MUST NOT treat a second host receiving the same id as a duplicate: one
     *           row per copy means two hosts holding RG_PROGRESSIVE_STRENGTH
     *           are two copies, and `expand` harvests both;
     *   MUST NOT touch any OTHER host — in particular it never junk-fills the
     *           hosts the bag did not reach; that is the per-game junk pass's
     *           job, after the fill (see THE BAG MODEL below);
     *   MUST NOT consume any RNG the world generation consumes (which is why
     *           both engines' junk covers are fixed items, not drawn).
     *
     * @return nonzero on success. Zero on a host the engine had itself offered
     *         as a candidate aborts the fill with
     *         RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED.
     */
    int (*place)(void* self, uint16_t hostCheck, SharedItem item);

    /**
     * Drop every placement this coordinator made, returning the engine's own
     * shuffled checks to unassigned. It must NOT touch the engine's graph, its
     * own restricted-pool placements, or anything the coordinator did not put
     * there.
     *
     * WHY THIS EXISTS, because it is the one call the audit's surface did not
     * have and it is not optional: the fill's dead-end recovery is a BATCH ROLL
     * BACK, and a roll-back that cleared only the coordinator's tables would
     * leave the previous attempt's placements inside both engines. The next
     * attempt would then see those hosts as assigned, run out of candidates, and
     * report a dead end that is an artefact of the retry rather than of the
     * world — turning one bad order into a permanently failing fill.
     *
     * Called from Combo_Logic_ResetPlacements(), hence at the start of every
     * fill attempt, and never inside a round.
     */
    void (*clearPlacements)(void* self);

    /**
     * End the round. Release whatever `beginQuery` set up and RESTORE THE
     * ENGINE'S COUPLING TO THE LIVE GAME — OoT re-points `Logic::mSaveContext`
     * at `&gSaveContext` here (audit §4.4). Called last, after `restore` and
     * after the placement re-apply.
     *
     * CALLED ONCE FOR EVERY `beginQuery` CALL, INCLUDING ONE THAT RETURNED ZERO.
     * So it must be safe on a round that never opened: an engine tests its own
     * "am I in a round" flag at the top and returns, because unwinding a detach
     * it never performed is worse than doing nothing. It is NOT called for a side
     * whose `snapshot` refused, because that side was never asked to begin.
     */
    void (*endQuery)(void* self);

    /**
     * OPTIONAL PAIR — both NULL, or both non-NULL. Registration refuses one
     * without the other, because a snapshot with no restore silently corrupts
     * the save and a restore with no snapshot silently reverts to nothing.
     *
     * `snapshot` captures everything this engine's queries will mutate (MM:
     * `gSaveContext` whole, plus the game-event queue depth — audit §4.4);
     * `restore` puts it back. One pair brackets the whole round.
     *
     * @return `snapshot` returns nonzero on success; zero aborts the round with
     *         RSBS_COMBO_LOGIC_ERR_ENGINE_REFUSED. A failed snapshot must never
     *         be followed by queries — that is the whole point of the return.
     *         Concretely: that side gets no `beginQuery`, hence no `endQuery`,
     *         and no `restore` either (there is nothing captured to put back).
     *         `restore` is called iff `snapshot` returned nonzero.
     */
    int (*snapshot)(void* self);
    void (*restore)(void* self);

    /**
     * OPTIONAL (ABI 4, ADR 0010 answer O10). How many triforce pieces THIS
     * HALF holds right now in the round — the pieces of the ONE shared count
     * that this engine's own pool contributes and this round has granted.
     *
     * AN ENGINE-NEUTRAL QUERY, not a game id: the coordinator never learns
     * which item is a piece. It sums the two halves' answers into the one count
     * (the MM half behind the ARRIVAL GATE, like MM's goal and hosts: a piece in
     * a Termina the player cannot enter is not a piece they hold) and compares
     * that sum with the frozen combo requirement the fill request carries. OoT:
     * the detached simulated save's `triforcePiecesCollected`; MM: the
     * snapshotted save's `foundTriforcePieces`. Both counters are granted
     * through each engine's own clamped give path (`assumeOwnItem`), so a
     * half can never answer more than its own pool holds.
     *
     * Valid only inside a round, like `goalReached`. Pure read. NULL means "this
     * engine has no piece machinery": a triforce-hunt fill over it is refused
     * with RSBS_COMBO_LOGIC_ERR_UNSUPPORTED_GOAL, and every other goal never
     * calls it. Trailing and optional so every ABI-3 initialiser keeps its
     * shape.
     */
    int (*triforcePieces)(void* self);
} ComboLogicEngine;

/**
 * Publish `engine` as the logic engine for `originGame`. Called once per game,
 * from that game's single-exe TU, or by a test for a stub.
 *
 * @param engine NULL UN-REGISTERS that game, so a test can install a stub and
 *               then restore the registry instead of leaving process-global
 *               state behind (the same courtesy
 *               `Combo_RegisterForeignItemPool(NULL, 0)` provides).
 * @return true if registered (or cleanly un-registered). False, with a logged
 *         reason and the registry UNCHANGED, when `originGame` is not a real
 *         game, `abiVersion` mismatches, a required pointer is NULL, or
 *         snapshot/restore are not both present or both absent.
 *
 * A second registration for the same game REPLACES the first and is logged:
 * two engines claiming one id-space is the ambiguity this surface exists to
 * prevent, so it must not pass silently.
 */
bool Combo_Logic_RegisterEngine(GameId originGame, const ComboLogicEngine* engine);

/** The registered engine for `originGame`, or NULL. Read-only. */
const ComboLogicEngine* Combo_Logic_GetEngine(GameId originGame);

// ============================================================================
// THE PLACEMENT TABLES
// ============================================================================
//
// TWO tables, keyed by HOST game, in PROCESS MEMORY ONLY. Nothing in this file is
// serialized, so nothing in this file is .redsave format. What persists of them
// is decided by ADR 0010 O7: the CROSSING rows (item origin != host) go to the
// crossing store (crossing_store.h, a .redsave v3 block, not a `reserved[]`
// carve), captured from and hydrated back into these tables; own-origin rows
// persist in each game's own save.

/** One placement. RAM only; no offset here is format. */
typedef struct {
    uint16_t hostCheck; // in hostGame's own check id-space
    uint16_t itemClass; // the bag row's RSBS_ITEMCLASS_* bit, carried through
    SharedItem item;    // origin-tagged; may be either game's origin
} ComboLogicPlacement;

/**
 * Empty both tables AND tell each registered engine to drop the placements this
 * coordinator gave it (`clearPlacements`). Called at the start of every fill
 * attempt — that is the batch roll-back, and it is only a roll-back if both
 * sides forget. Also available to tests for isolation.
 */
void Combo_Logic_ResetPlacements(void);

/**
 * AUTHOR one placement directly: record it in the coordinator's table and hand
 * it to the owning host engine through `place`, exactly as the fill does.
 *
 * This is the entry a caller uses when the placement was DECIDED ELSEWHERE — the
 * locks author known-shape worlds with it, and the spoiler-LOAD path will need
 * precisely this shape to rebuild both tables from a spoiler's foreign section
 * without either game's header in scope (the inverse
 * `Combo_GetForeignItemByNameFor` already serves).
 *
 * IT DOES NOT COMPOSE WITH Combo_Logic_RunFill. Every fill attempt begins by
 * emptying both tables and both engines (see the reset paragraph at
 * Combo_Logic_RunFill), so authoring rows here and then asking the fill to do
 * "the rest of the bag" discards every row authored. Authoring and filling are
 * alternatives for one world, not stages of one.
 *
 * IT PROVES NOTHING. Authoring bypasses the round, so it makes no reachability
 * claim about the host and no GOAL claim about the world; proof is
 * Combo_Logic_RunFill's exit condition and only ever that. A caller that means
 * "generate a world" must not build one out of these.
 *
 * @return false if `hostGame` is not a real game, the item carries no origin,
 *         the host is already assigned, the table is full, or the host engine is
 *         absent or refused. On false NOTHING was recorded.
 */
bool Combo_Logic_Place(GameId hostGame, uint16_t hostCheck, SharedItem item, uint16_t itemClass);

/** How many placements `hostGame` holds, or 0 for a non-game. */
int Combo_Logic_PlacementCount(GameId hostGame);

/** The `index`-th placement of `hostGame`, in insertion order (which is the
 *  fill's own order, so it is world-visible and stable). False out of range. */
bool Combo_Logic_PlacementAt(GameId hostGame, int index, ComboLogicPlacement* out);

/** The placement on (hostGame, hostCheck), or false if that host is unassigned.
 *  This is the coordinator's occupancy authority. */
bool Combo_Logic_GetPlacement(GameId hostGame, uint16_t hostCheck, ComboLogicPlacement* out);

/**
 * HYDRATE both tables from rows decided and persisted elsewhere (ADR 0010 O7:
 * the crossing store, crossing_store.h), WITHOUT calling either engine.
 *
 * WHY NOT Combo_Logic_Place. Place hands every row to its host engine's `place`,
 * which writes the host game's own table (OoT's ItemLocation, MM's
 * RANDO_SAVE_CHECKS in the LIVE gSaveContext). At an arrival or a load those
 * tables already hold the result, because each game's save persisted it; and in
 * a process where MM has not booted, the live MM SaveContext is not the save
 * being loaded at all, so an engine write there would be a write into the
 * wrong world that a later `clearPlacements` would then "restore" from.
 * Hydrating records the rows and nothing else.
 *
 * ALL OR NOTHING: every row is validated first (a real host game, an origin
 * tag, at most RSBS_COMBO_LOGIC_PLACEMENT_CAP rows per host, no host twice
 * within a game); on refusal the tables are untouched. On success both tables
 * hold exactly the given rows in the given order, the round and surplus
 * bookkeeping is reset, and neither engine was called.
 *
 * Like Combo_Logic_Place it PROVES NOTHING and does not compose with
 * Combo_Logic_RunFill (every attempt starts by emptying the tables).
 */
bool Combo_Logic_HydrateTables(const ComboLogicPlacement* ootHosted, int ootCount, const ComboLogicPlacement* mmHosted,
                               int mmCount);

/**
 * A stable FNV-1a digest over both tables in order (host game, host check,
 * origin, id, class). Two fills with the same digest placed identically.
 *
 * IT IS NOT A WORLD DIGEST and must never be presented as one: it covers this
 * coordinator's tables, not either game's own fill output, its spoiler, or any
 * `.redsave` byte. Its purpose is the same-seed / different-seed locks and
 * whatever the follow-on lanes need to compare two coordinator runs.
 */
uint32_t Combo_Logic_PlacementDigest(void);

// ============================================================================
// GOAL EVALUATION
// ============================================================================

/**
 * The GOAL expression over the two halves' own booleans (ADR 0010 D1 §1.1).
 *
 * @param goal an RSBS_COMBO_GOAL_* value (the FROZEN record's, never a CVar's)
 * @return 1 provable, 0 not, and -1 when `goal` is not a boolean over the two
 *         halves. RSBS_COMBO_GOAL_TRIFORCE_HUNT is such a goal: its expression
 *         is a COUNT (answer O10), so it answers -1 here and is evaluated by
 *         Combo_Logic_EvaluateTriforceHunt below. A caller must distinguish -1
 *         from 0.
 *
 * `beat-either` is a PLAIN OR and the coordinator never narrows it to an XOR:
 * an unbeatable half is permitted, both halves provable is a welcome outcome,
 * and nothing anywhere may bias toward asymmetry (ADR 0010 §1.2 / answer O1).
 */
int Combo_Logic_EvaluateGoal(uint8_t goal, int ootGoalReached, int mmGoalReached);

/**
 * The triforce-hunt GOAL expression (ADR 0010 answer O10): the ONE shared piece
 * count across both worlds against the frozen combo requirement.
 *
 * @param sharedPieces the two halves' `triforcePieces` answers summed (the MM
 *        half behind the arrival gate); negative means a half could not answer
 * @param required the frozen combo requirement (Combo_TriforceHuntRequired,
 *        triforce_hunt.h — the record's, never a CVar's)
 * @return 1 when `sharedPieces >= required`, 0 when fewer, -1 when either input
 *         is unusable (a negative count, or a zero requirement, which describes
 *         no hunt).
 *
 * `>=`, not `==`: the proof asks whether the player CAN hold the requirement.
 * The runtime win arms test `==` because they fire once, on the give that
 * reaches it (Combo_TriforceHuntOnPieceGiven).
 */
int Combo_Logic_EvaluateTriforceHunt(int sharedPieces, uint16_t required);

// ============================================================================
// ONE ROUND, EXPOSED
// ============================================================================

/** `ComboLogicBagItem.bagFlags`: this row is a SURPLUS COPY — a copy beyond what
 *  the GOAL proof may rely on (a plentiful duplicate). See THE BAG MODEL below.
 *  RAM only; not format. */
#define RSBS_COMBO_BAG_SURPLUS 0x0001u
/** Every bag flag this build understands. A row carrying any other bit is
 *  refused (RSBS_COMBO_LOGIC_ERR_BAD_REQUEST) rather than silently ignored. */
#define RSBS_COMBO_BAG_FLAGS_KNOWN RSBS_COMBO_BAG_SURPLUS

/** The assumed set / bag element: ONE COPY of an origin-tagged item, the class
 *  it was admitted under, and its bag flags. The class is CARRIED, not filtered
 *  on — see the fill. Two copies of one id are two rows. */
typedef struct {
    SharedItem item;    // originGame must be GAME_OOT or GAME_MM
    uint16_t itemClass; // one RSBS_ITEMCLASS_* bit, or 0 when the caller has none
    uint16_t bagFlags;  // RSBS_COMBO_BAG_* bits; 0 = a REQUIRED copy (the default)
} ComboLogicBagItem;

typedef struct {
    const ComboLogicBagItem* assumed; // the assumed set A; NULL iff assumedCount == 0
    int assumedCount;
    uint8_t goal; // RSBS_COMBO_GOAL_*
    /** RSBS_COMBO_GOAL_TRIFORCE_HUNT only: the frozen combo requirement
     *  (Combo_TriforceHuntRequired). Ignored by every other goal; 0 under
     *  triforce-hunt leaves the expression unevaluated (-1). */
    uint16_t triforceRequired;
} ComboLogicRoundRequest;

typedef struct {
    int status;     // RSBS_COMBO_LOGIC_*
    int iterations; // inner alternations actually run
    int crossingOpenOoT;
    int crossingOpenMM;
    int goalOoT;        // the OoT half's own answer
    int goalMM;         // the MM half's, AFTER the arrival gate
    int goalExpression; // GOAL(goalOoT, goalMM); -1 when the goal has no evaluator
    int candidatesOoT;  // reached, coordinator-unassigned hosts
    int candidatesMM;   // ditto, and zero while the arrival gate is closed
    int exchanged;      // crossing exchanges performed this round
    /** Was every host the coordinator has already placed on reached in this
     *  round? 1 yes, 0 no, and -1 when the round did not get far enough to
     *  evaluate it (an engine refusal or a malformed request). It is evaluated
     *  INSIDE the round because `checkReached` is only valid before teardown —
     *  which is why the `all-reachable` rung cannot be a post-pass. */
    int allHostsReached;
    /** Triforce-hunt rounds only (ADR 0010 answer O10); -1 otherwise, and -1 for
     *  a half whose engine has no `triforcePieces`. The OoT half's own answer,
     *  the MM half's AFTER the arrival gate, and their sum: the ONE count the
     *  expression compared with the requirement. */
    int triforcePiecesOoT;
    int triforcePiecesMM;
    int triforcePieces;
} ComboLogicRoundResult;

/**
 * Run ONE round and report what it saw, leaving the placement tables untouched.
 *
 * This is the coordinator's smallest observable unit and it is public for two
 * reasons beyond the locks: epic #645's first work item is measuring the cost
 * of one linked round against the #582 creation budget, and its second is
 * whether an assumed fill over MM's forward-authored graph converges — both are
 * questions about this function.
 *
 * @return the status, also written to `out->status` when `out` is non-NULL.
 */
int Combo_Logic_RunRound(const ComboLogicRoundRequest* req, ComboLogicRoundResult* out);

/**
 * READ-ONLY, TEST ONLY: the candidate host SET behind the latest round's
 * `candidatesOoT` / `candidatesMM` for `hostGame`, in the engine's order.
 *
 * Why it exists (ADR 0010 answer O6, the `combo-logic-monotonicity` row's G4): a
 * COUNT cannot see a host lost in the same step another is gained, so "the
 * coordinator never reaches fewer hosts over a longer bag prefix" is asserted on
 * the sets. It reads the buffer the round already filled and writes nothing.
 * At most `cap` written, the TOTAL returned; -1 for a game with no buffer.
 */
int Combo_Logic_TestLastCandidates(GameId hostGame, uint16_t* out, int cap);

// ============================================================================
// THE BAG MODEL — copies, surplus, filler and traps (operator ruling 2026-09-26)
// ============================================================================
//
// The operator's note on the ruling: "there are usually options here. like
// plentiful drops is an option (and then depending on the options there might
// be more checks than items. ice traps are a thing too for randos)." So the bag
// has to be right in four shapes, and this block is the whole rule for each.
//
// 1. COPIES. The bag holds ONE ROW PER COPY. Not a row with a count: a copy is
//    what lands on a host, each host holds exactly one copy, and the placement
//    table, the spoiler and the ADR 0002 boundary (`SharedItem` + host id + host
//    origin, nothing else) are all per copy already — a count would have to be
//    split at the draw and re-merged everywhere else. The row's identity is its
//    BAG INDEX, which is stable for the call; nothing about it crosses into an
//    engine. Every copy is assumed once per round (see `assumeOwnItem`).
//
// 2. REQUIRED vs SURPLUS. A row is REQUIRED (bagFlags 0) or SURPLUS
//    (RSBS_COMBO_BAG_SURPLUS): a copy BEYOND what the proof may rely on — OoT's
//    `RO_ITEM_POOL_PLENTIFUL` extras (`item_pool.cpp` `plentifulPool`), MM's
//    `RO_PLENTIFUL_ITEMS` duplicates (`GeneratePools.cpp`). The caller (each
//    game's pool builder, via its bag export) marks them; the coordinator never
//    guesses. What the two fills agree on, and what this rule takes from them:
//    a plentiful copy goes in ONLY WHERE THERE IS ROOM, room is counted over
//    ALL empty locations (OoT: `locCount = ctx->CountEmptyLocations(false)`;
//    MM: replaceable items over its whole pool), and NEITHER ever gives up a
//    base-pool item for one (OoT asserts `itemPool.size() <= locCount` before
//    plentiful is considered). Where they DIFFER is the shortfall, and the
//    coordinator matches neither by itself (see shape 3). So:
//      - The proving phase places the REQUIRED rows only, and assumes only the
//        unplaced REQUIRED rows. The GOAL is proved with every surplus copy
//        ABSENT. A surplus copy can therefore never be load-bearing, which is
//        what makes it droppable, and a caller that marks a copy the world
//        needs as surplus gets ERR_GOAL_UNPROVABLE — the honest answer.
//      - AFTER the exit condition holds, the surplus rows are placed IN BAG
//        ORDER, each on a host drawn uniformly (private RNG) from the RUNG'S
//        host source:
//          `beatable`, `none`: EVERY empty host, reached or not — a surplus
//            copy is not load-bearing, so an unreached host is a harmless place
//            for it, and it is the room both native fills count. (An earlier
//            version drew from the proven world's REACHED hosts under
//            `beatable` too, and so dropped copies while empty hosts remained.)
//          `all-reachable`: only the final proof round's reached, unassigned
//            hosts (arrival gate applied), because that rung promises every
//            placed host is reached. Placing an item can only grow
//            reachability, so every one of those hosts stays reached.
//        Either way the proof stays true, and a confirming round is run after
//        the surplus placements to MEASURE that rather than assume it (a
//        failure there is ERR_NON_MONOTONE).
//
// 3. MORE BAG THAN HOSTS (plentiful surplus). When the host supply runs out
//    during the surplus phase, every surplus row not yet placed is DROPPED.
//    Because the phase walks the surplus rows in bag order, the dropped rows are
//    exactly the LAST ones in bag order — last-first — and which rows they are
//    is a pure function of (bag, seed, engines), reported through
//    `surplusDropped`/`droppedDigest` and Combo_Logic_SurplusDroppedAt. A
//    REQUIRED row is NEVER dropped: running out of hosts for one is the existing
//    dead end (roll back / ERR_NO_CANDIDATE), because dropping a required copy
//    could silently make the stated world unprovable, which neither native fill
//    ever does.
//
//    LAST-FIRST IS THE COORDINATOR'S RULE, NOT EITHER NATIVE FILL'S, and BAG
//    ORDER IS THE CALLER'S INSTRUMENT for matching a native one:
//      - OoT's native shortfall keeps a RANDOM subset: when the plentiful pool
//        does not fit, it tops up with `RandomElement(plentifulPool, true)`
//        until `locCount` (item_pool.cpp). A caller that wants OoT's rule
//        shuffles its OoT surplus rows WITH OoT'S OWN RNG before building the
//        bag; the last-first tail of a random order is then a random subset.
//      - MM's native rule is all-or-nothing: it adds the whole plentiful list
//        only `if (replaceableItems > plentifulItems.size())` (GeneratePools.cpp).
//        A caller that wants MM's rule marks MM rows surplus only when the whole
//        list fits, and leaves them out of the bag otherwise.
//    Neither bag export marks surplus yet (see WHO MARKS SURPLUS below), so no
//    caller exercises either choice today.
//
// 4. MORE HOSTS THAN BAG (filler), and TRAPS. The coordinator places BAG ROWS
//    AND NOTHING ELSE. Hosts no row landed on are LEFTOVER, enumerated by
//    Combo_Logic_LeftoverHosts and counted in `leftoverHostsOoT/MM`, and they
//    belong to EACH GAME'S OWN PER-GAME PASS after the fill. That pass places
//    two different things, and the difference matters for traps:
//      - JUNK, drawn to fill whatever is left: OoT's `FastFill`/`GetJunkItem()`,
//        MM's balance step (`OnFileCreate.cpp`, which appends `RI_JUNK` until
//        the item pool matches the check pool).
//      - TRAPS, which in BOTH ports are COUNTED POOL ROWS the settings fix, NOT a
//        product of the junk draw: MM pushes `RI_TRAP` × `RO_TRAP_AMOUNT` into
//        its item pool under `RO_SHUFFLE_TRAPS` (GeneratePools.cpp; a
//        RITYPE_LESSER row, dressed at runtime by `gRando.Traps.*`); OoT adds
//        its fixed ice traps (`RSK_BASE_ICE_TRAPS` plus
//        `RSK_ADDITIONAL_ICE_TRAPS`) with `AddFixedItemToPool` and converts
//        `RSK_ICE_TRAP_PERCENT` of its junk to `RG_ICE_TRAP` DURING pool
//        generation (item_pool.cpp), with `GetJunkItem()` supplying more only
//        in the late fills; `possibleIceTrapModels` disguises them.
//    So the per-game pass must CARRY each game's trap count from its own pool
//    builder and place exactly that many traps (capped by the room, as OoT's
//    own fixed-trap insert is) on THAT GAME'S OWN leftover hosts, then junk the
//    rest. A pass that only ran the junk draw would give a trap-enabled world
//    zero MM traps and lose OoT's fixed ice traps. Neither pass is built yet;
//    this is the rule it must follow (increment 4's bag builder).
//
//    A TRAP DOES NOT CROSS — BY CALLER CONVENTION, NOT BY CONSTRUCTION. The
//    coordinator checks only a row's origin game and bag flags, so a trap row
//    handed to it WOULD be placed on the union of both games' hosts. What keeps
//    traps per-game today is that no bag export puts one in the bag (MM's pool
//    export excludes `RI_TRAP` in ComboLogicEngineSingleExe.cpp; OoT's exports
//    advancement items only). A REFUSAL — a trap-class row rejected at the bag —
//    needs the O8 classification table (lane K5, `src/common/shared_items.*`)
//    wired in; until then the rule rests on the caller. Whether a host could
//    render a FOREIGN trap is out of scope this increment. The coordinator
//    cannot run either per-game pass itself — they consume each game's own fill
//    RNG, which no call on this surface may touch — so it hands over the exact
//    host list and stops.
//
// (5) EXACT FIT is the degenerate case of both: nothing dropped, nothing
//    leftover. It is locked as its own shape because it is where an off-by-one
//    in either rule would show.

// ============================================================================
// THE SINGLE-BAG ASSUMED FILL
// ============================================================================

typedef struct {
    const ComboLogicBagItem* bag; // the union bag; NULL iff bagCount == 0
    int bagCount;
    uint8_t goal;      // RSBS_COMBO_GOAL_*  } both from the FROZEN record,
    uint8_t logicRung; // RSBS_COMBO_RUNG_*  } never from a live CVar
    /**
     * The coordinator's PRIVATE RNG seed, derived by the caller from the frozen
     * identity (`gComboCtx.sharedRandoSeed`, `comboSettingsHash`, ...). It is
     * never a game's RNG: both engines' RNGs belong to their own fills, a query
     * must consume none, and a coordinator that drew from either would couple
     * the world to the number of rounds the search happened to run.
     */
    uint32_t seed;
    /** Batch roll-backs within this seed; 0 means RSBS_COMBO_LOGIC_FILL_RETRIES.
     *  Re-rolling the SEED is the attempt ladder's job, one level up. */
    int maxAttempts;
    /** RSBS_COMBO_GOAL_TRIFORCE_HUNT only (ADR 0010 answer O10): the frozen
     *  combo requirement, from the FROZEN triforce record
     *  (Combo_TriforceHuntRequired), never a CVar. Ignored by every other goal.
     *  Under triforce-hunt a zero is refused as RSBS_COMBO_LOGIC_ERR_BAD_REQUEST,
     *  and so is a pair of engines without `triforcePieces` — as
     *  RSBS_COMBO_LOGIC_ERR_UNSUPPORTED_GOAL — both before any attempt. */
    uint16_t triforceRequired;
} ComboLogicFillRequest;

typedef struct {
    int status;
    int attempts; // attempts consumed, including the successful one; 0 when the
                  // request was refused before any attempt ran
    int placed;   // placements this call put in the tables; 0 on a pre-attempt refusal
    int rounds;   // rounds run across every attempt; always 0 under rung `none`
    bool goalProven;      // the exit condition was evaluated and held
    bool proofSkipped;    // rung `none`: no proof was attempted (goalProven is false)
    bool allHostsReached; // rung `all-reachable` only: every placed host was reached
    uint32_t placementDigest; // 0 on a pre-attempt refusal (see the note at RunFill)
    // --- THE BAG MODEL's accounting (see that block). All 0 on a pre-attempt
    //     refusal, and describing the LAST attempt otherwise. ------------------
    int requiredPlaced; // REQUIRED rows placed (== the required count on success)
    int surplusPlaced;  // SURPLUS rows placed after the proof held
    int surplusDropped; // SURPLUS rows dropped because the host supply ran out
    uint32_t droppedDigest; // FNV-1a over the dropped rows (bag index, origin, id);
                            // the offset basis when nothing was dropped
    int leftoverHostsOoT;   // hosts no row landed on: each game's own per-game pass
    int leftoverHostsMM;    //   fills these (its counted traps, then junk)
} ComboLogicFillResult;

/**
 * THE FILL. One bag, both games' hosts, the GOAL expression as the exit
 * condition (ADR 0010 D3/D4, increment 3).
 *
 * The algorithm, which is OoT's own assumed fill lifted one level (audit §4.3):
 * shuffle the REQUIRED rows with the private RNG; for each one, run a round with
 * every OTHER unplaced REQUIRED row assumed (one `assumeOwnItem` per copy), take
 * the union of both sides' candidate hosts, pick one uniformly, and place it on
 * its owning side. On an empty candidate set, roll the whole batch back and
 * retry with a different deterministic order. When the required rows are all
 * placed, run one final round with NOTHING assumed and require the GOAL
 * expression — that requirement is the loop's exit condition, never a check
 * bolted on after it. Only then are the SURPLUS rows placed, in bag order, on
 * the rung's surplus host source (every empty host under `beatable`; the proven
 * world's reached hosts under `all-reachable`), the ones that find no host are
 * dropped, and a confirming round re-checks the exit condition. THE BAG MODEL
 * block above is the whole rule for surplus, drops and leftover hosts.
 *
 * THE RUNGS, and what each one actually does. They share the bag, the RNG, the
 * uniform union draw and the two tables; they do NOT share the host source,
 * because ADR 0010 D5's base mode is "bag, then randomly distribute" and audit
 * §4.3 spells that out as "the round is skipped and hosts are drawn from all
 * empties":
 *   RSBS_COMBO_RUNG_NONE          - NO ROUND IS RUN, at all. Hosts are drawn
 *                                   from `allEmptyHosts` on both sides, the
 *                                   arrival gate does not apply (a rung that
 *                                   makes no reachability claim cannot gate on
 *                                   one), `rounds` is 0, and there is exactly
 *                                   one attempt: nothing here can dead-end for
 *                                   a logic reason, so nothing can be fixed by
 *                                   re-shuffling. Nothing is proved:
 *                                   `proofSkipped` is true and `goalProven` is
 *                                   false, and a caller must not read "not
 *                                   proven" as "failed".
 *   RSBS_COMBO_RUNG_BEATABLE      - a round per bag item over REACHED empty
 *                                   hosts, then a final round with nothing
 *                                   assumed in which the GOAL expression must
 *                                   hold.
 *   RSBS_COMBO_RUNG_ALL_REACHABLE - the same, plus: every host the COMBO FILL
 *                                   placed on must be reached in that final
 *                                   round.
 *
 * The all-reachable rung's obligation is deliberately over PLACED hosts and not
 * over every location in either world. "Every location reachable" is each half's
 * own existing strictness axis (`RSK_ALL_LOCATIONS_REACHABLE` and MM's
 * analogue), which ADR 0010 §1.2 explicitly keeps per-half and composes with any
 * GOAL; the pair-level obligation this rung adds on top is that nothing the
 * SINGLE BAG distributed ended up somewhere the player cannot stand. Widening it
 * to "every host in both worlds" would duplicate that per-half axis at the pair
 * level, which §1.2 kept per-half deliberately. (`allEmptyHosts` could now
 * enumerate the wider set — it exists for the `none` rung — so the narrow
 * reading is a decision here, not a limitation of the surface.)
 *
 * DETERMINISM: the whole result is a pure function of (`bag` contents — flags
 * included — and order, `goal`, `logicRung`, `seed`, `maxAttempts`, the two
 * registered engines). Same inputs, same placements AND THE SAME DROPS, byte for
 * byte.
 *
 * THE FILL OWNS THE TABLES, AND IT TAKES THEM EMPTY. Every attempt — the first
 * one included, and the single attempt the `none` rung runs — begins with
 * Combo_Logic_ResetPlacements(), so whatever the two tables held when the call
 * arrived is DISCARDED before the first item is placed, and discarded from both
 * ENGINES too (that reset calls each one's `clearPlacements`). This is stated here
 * and not only at the reset, because the caller who needs to know is the one
 * standing at this call with rows already in the tables: there is no
 * keep-existing-placements mode, and a fill is never a continuation of an
 * authored partial world (see Combo_Logic_Place). Only a refusal taken BEFORE any
 * attempt leaves the tables alone — the paragraph below.
 *
 * ON FAILURE OF AN ATTEMPT the placement tables hold the LAST attempt's partial
 * state; a caller that means to discard them calls Combo_Logic_ResetPlacements().
 *
 * ON A REFUSAL BEFORE ANY ATTEMPT — a malformed request, an unpinned rung, an
 * unsupported GOAL, a missing engine — NOTHING is touched: no engine is called,
 * the tables keep whatever they already held, and `placed` and `placementDigest`
 * are reported as 0 rather than describing tables this call never looked at. A
 * caller that wants the tables' contents after such a refusal reads them through
 * Combo_Logic_PlacementCount / Combo_Logic_PlacementDigest, which are about the
 * tables; the result struct is about the call.
 *
 * @return the status, also written to `out->status` when `out` is non-NULL.
 */
int Combo_Logic_RunFill(const ComboLogicFillRequest* req, ComboLogicFillResult* out);

/** How many SURPLUS rows were dropped by the fill attempt that BUILT THE CURRENT
 *  TABLES. The record lives and dies with the tables: Combo_Logic_ResetPlacements
 *  (which every attempt begins with) zeroes it, and a PRE-ATTEMPT REFUSAL touches
 *  neither — so after a refused call this still reports the PREVIOUS attempt's
 *  drops, beside that attempt's placements, while the refused call's own
 *  `ComboLogicFillResult.surplusDropped` is 0 (the result describes the call, the
 *  record describes the tables). Locked by combo-logic-bag-model S-f. */
int Combo_Logic_SurplusDroppedCount(void);

/** The `index`-th dropped row's BAG INDEX (into the request's `bag`), in the
 *  order the rows were dropped — which is bag order, so the dropped rows are the
 *  trailing surplus rows. False out of range. */
bool Combo_Logic_SurplusDroppedAt(int index, int* outBagIndex);

/**
 * The LEFTOVER hosts of `hostGame`: every host its engine offers through
 * `allEmptyHosts` that the coordinator's table does not hold, in the engine's
 * own stable order. This is exactly the host list that game's OWN per-game pass
 * must fill after the fill — that game's counted trap rows, then junk
 * (THE BAG MODEL, shape 4).
 *
 * Legal outside any round (it is `allEmptyHosts` plus the occupancy filter).
 * Same truncation contract as the engine enumerations: at most `cap` written,
 * the TOTAL returned; -1 when `hostGame` has no engine or the engine exceeds
 * RSBS_COMBO_LOGIC_HOST_CAP (refused, never truncated).
 */
int Combo_Logic_LeftoverHosts(GameId hostGame, uint16_t* out, int cap);

// ============================================================================
// DELIBERATELY ABSENT — do not read these as oversights
// ============================================================================
//
//  - ANY PRODUCTION WIRING. No shipping TU registers an engine and no creation
//    seam calls the fill. The two engine implementations are two follow-on
//    lanes; until both exist a paired fill cannot run at all, which is why
//    Combo_Logic_RunFill refuses with one engine instead of half-filling.
//  - THE O7 BOUNDARY CARVE. Answered (ADR 0010 amendment 2026-09-27): no
//    `reserved[]` carve; the crossing rows persist in crossing_store.h's block
//    and come back through Combo_Logic_HydrateTables. The tables stay RAM.
//  - THE O8 CLASSIFICATION TABLE. `ComboLogicBagItem.itemClass` is carried
//    from the caller and recorded on the placement; the coordinator filters
//    nothing by it. When the single-owner table lands in
//    `src/common/shared_items.*` (answer O8) the class is read from there
//    instead, and any narrowing belongs to the pool DRAW
//    (`Combo_ForeignPoolDrawFor`) which already runs before the bag exists —
//    the six membership criteria run FIRST and the bitset selects among the
//    survivors (ADR 0011 decision 3.1), an ordering this file may not weaken.
//  - (no longer absent) THE O10 SHARED TRIFORCE COUNT. triforce-hunt is
//    evaluated as the sum of both engines' `triforcePieces` against the frozen
//    requirement the request carries (Combo_Logic_EvaluateTriforceHunt); the
//    record, the shared count and the win arms live in triforce_hunt.h. It is
//    refused only over an engine without the query, or with no requirement.
//  - THE SPOILER. One artifact for the pair is #564 V23 / audit P11; this
//    coordinator exposes its tables and stops there.
//  - THE ATTEMPT LADDER. Re-rolling the seed on a failed fill is the layer
//    above; the coordinator's retries are batch roll-backs within ONE seed.
//  - PER-GAME PASSES. OoT's restricted-pool fills and both games' junk
//    `FastFill`s stay per-game and are not this bag (audit amendment 2). The
//    coordinator hands each game its leftover host list
//    (Combo_Logic_LeftoverHosts) and runs neither junk pass itself: both draw
//    from their own game's fill RNG, which nothing on this surface may consume.
//  - TRAPS IN THE BAG. A trap is a counted row of its own game's pool, placed by
//    that game's own per-game pass on its own leftover hosts (THE BAG MODEL,
//    shape 4). It stays out of this bag BY CALLER CONVENTION: nothing here can
//    tell a trap row from any other row, because the O8 classification table
//    (lane K5, `src/common/shared_items.*`) is not wired into the bag yet, and a
//    trap row that WAS handed over would be placed on either game's hosts. When
//    the table is wired, a trap-class row is REFUSED at the bag, not placed —
//    rendering a foreign trap is out of scope this increment.
//  - WHO MARKS SURPLUS. `RSBS_COMBO_BAG_SURPLUS` is set by the caller; neither
//    engine exports its plentiful copies as such yet (their pool exports are
//    the measurement bridges, over the shipped profile, where plentiful is
//    off). That export is increment 4's bag builder.
//  - THE CROSSING EDGE'S TIME-OF-DAY TERMS (answer O2's Day-1 re-stamp and
//    reset-time guard). Those are authored inside the engines, behind
//    `crossingOpen`; the coordinator only reads the resulting fact.

#ifdef __cplusplus
}
#endif

#endif // RSBS_COMMON_COMBO_LOGIC_H
